import { defineConfig } from 'tsdown'

// Public subpaths share the verifier's process-local credential registry.
export default defineConfig({
  entry: [
    'index',
    'supply',
    'tools',
    'plugin-draft-tools',
    'private-mac-video-tool',
    'comfy-video-public-contract',
    'comfy-local-probe',
    'comfy-video-sqlite-attempt-ledger',
    'protocol',
    'fanout/index',
    'validation',
    'executor',
    'model-adapter',
    'legal-document-plugin',
    'local-execution-admission',
    'agent-router',
    'pc-task-surface',
    'task-state',
    'task-store',
    'submission-ledger',
    'envelope-security',
    'native-h3-binding',
    'native-h3-device-proof',
    'native-h3-review',
    'native-h3-presence',
    'native-h3-task-lease',
    'native-h3-v2-evidence',
    'contributor-policy',
    'resource-observer',
    'scheduler',
    'node-protocol',
    'node-session',
    'node-transport',
    'employee-task-coordinator',
    'capability-manifest',
    'local-plugin-runtime',
    'routing-contract',
    'router',
    'router-adapter',
    'commerce-image-workflow',
    'plugin-contract',
    'plugin-market',
    'node-capability',
    'resident-loop',
    'task-workspace',
    'task-output',
    'result-assets',
    'local-task-runner',
    'resident/index',
    'transport/memory-session',
    'edge-worker/connection',
    'edge-worker/file-task-contract',
    'edge-worker/artifact-read',
    'edge-worker/artifact-upload-file',
    'edge-worker/polled-verification',
    'transport/edge-worker-session',
  ].map(entry => `lib/types/${entry}.js`),
  outDir: 'lib',
  format: ['esm'],
  platform: 'node',
  target: 'es2024',
  fixedExtension: false,
  dts: false,
  clean: false,
})
