/** Ordinary H3 setup labels distinguish local trials from publication and supply. */
export const h3CanonicalZh = {
  h3CanonicalTitle: '接入本机视频生成',
  h3CanonicalIntro: '让这台电脑通过技能市场为其他电脑生成视频。先检查环境，再试跑两段视频。',
  h3CanonicalOpen: '开始接入',
  h3CanonicalClose: '收起',
  h3CanonicalFrameHint: '选择一张 PNG 图片作为测试首帧。模型和工作流由已安装的 H3 服务提供。',
  h3CanonicalAdvanced: '高级设置',
  h3CanonicalAdvancedHint: '通常无需修改。服务必须运行在这台电脑上。',
  h3CanonicalNegative: '希望避免的画面（可选）',
  h3CanonicalInspected: '已连接本机 H3 服务，图片检查通过。保存后即可试跑。',
  h3CanonicalSaved: '配置已保存，接下来分别试跑两段五秒视频。',
  h3CanonicalTrial: '试跑视频',
  h3CanonicalTrialHint: '两次测试分别使用本机 GPU，可能需要几分钟。不收取平台费用。每次都由你点击开始。',
  h3CanonicalRunFirst: '试跑第一段视频',
  h3CanonicalRunSecond: '试跑第二段视频',
  h3CanonicalFirstReady: '第一段视频已核验，接下来试跑第二段。',
  h3CanonicalReady: '两段视频均已核验，可以创建技能。发布、审核和开启接单仍是后续步骤。',
  h3CanonicalPending: '本机正在生成或核验视频，请保持程序运行。',
  h3CanonicalUnknown: '这次测试的结果尚未确认。请查看本机服务和测试状态，不会自动重复生成。',
  h3CanonicalFrameInvalid: '请选择有效的 PNG 图片，大小不超过 16 MiB。',
  h3CanonicalSoftware: '本机 H3 服务尚未接入受支持的版本。请更新并启动标准服务，再检查环境。',
  h3CanonicalRecord: '当前配置或测试记录需要重新核对，请保留现有记录并联系支持。',
  h3CanonicalTwoTrials: '请先完成两段独立测试视频，再创建技能。',
  h3CanonicalLegacy: '旧版 H3 接入设置',
  h3CanonicalRequirementsTitle: '接单前，这台电脑需要什么',
  h3CanonicalRequirementsIntro: '以下四项必须在同一台 Windows 电脑上配齐。检查环境会核对整套服务身份；两次真实出片通过后，还需发布审核、设备绑定和接单时复核。',
  h3CanonicalComfyRequirement: 'ComfyUI 与本机 H3 服务',
  h3CanonicalModelsRequirement: 'H3 所需的五类模型文件',
  h3CanonicalPluginsRequirement: '工作流依赖的插件',
  h3CanonicalWorkflowRequirement: '指定的四步 qs_new4 工作流',
  h3CanonicalRequirementUnchecked: '待核验',
  h3CanonicalRequirementInspected: '本次服务身份已核对',
  h3CanonicalRequirementTrial: '上次本机出片已核验',
  h3CanonicalInstallGuide: '缺少任一项时，先在这台电脑安装并启动受支持的版本，再点“检查环境”。目前没有可核验的签名安装源，客户端不会自动下载模型、插件或工作流。',
  h3CanonicalSupplyGate: '此处只完成本机接入，不会开启接单。环境不完整、测试未通过或结果不确定时，视频供给保持关闭。',
  h3CanonicalServiceOffline: '无法连接这台电脑的 H3 服务。请先启动 ComfyUI 与本机 H3 服务，再检查环境。',
  h3CanonicalIdentityUnverified: '本机模型、插件或四步工作流的身份尚未核验。请检查已安装版本，再检查环境；不会猜测具体缺少哪个文件。',
} as const

/** English labels use the same semantic states as the Chinese setup page. */
export const h3CanonicalEn: Record<keyof typeof h3CanonicalZh, string> = {
  h3CanonicalTitle: 'Connect local video generation',
  h3CanonicalIntro: 'Let this PC generate videos for other computers through the skill market. Check the environment and run two local trials.',
  h3CanonicalOpen: 'Start setup', h3CanonicalClose: 'Collapse',
  h3CanonicalFrameHint: 'Choose a PNG first frame. The installed H3 service provides the model and workflow.',
  h3CanonicalAdvanced: 'Advanced settings', h3CanonicalAdvancedHint: 'Usually no changes are needed. The service must run on this computer.',
  h3CanonicalNegative: 'Images to avoid (optional)',
  h3CanonicalInspected: 'Connected to the local H3 service and checked the image. Save to begin trials.',
  h3CanonicalSaved: 'Configuration saved. Run two separate five-second videos next.',
  h3CanonicalTrial: 'Run trial videos',
  h3CanonicalTrialHint: 'Each trial uses the local GPU and may take several minutes. There are no platform charges. Start each trial explicitly.',
  h3CanonicalRunFirst: 'Run the first video', h3CanonicalRunSecond: 'Run the second video',
  h3CanonicalFirstReady: 'The first video is verified. Run the second video next.',
  h3CanonicalReady: 'Both videos are verified. Create a skill next; publication, review and supply activation are separate steps.',
  h3CanonicalPending: 'This PC is generating or verifying a video. Keep the program running.',
  h3CanonicalUnknown: 'This trial is not confirmed. Check the local service and trial status. No generation is repeated automatically.',
  h3CanonicalFrameInvalid: 'Choose a valid PNG image no larger than 16 MiB.',
  h3CanonicalSoftware: 'Update and start the supported local H3 service before checking the environment.',
  h3CanonicalRecord: 'The configuration or trial record needs checking. Keep the records and contact support.',
  h3CanonicalTwoTrials: 'Complete two independent trial videos before creating a skill.',
  h3CanonicalLegacy: 'Legacy H3 setup',
  h3CanonicalRequirementsTitle: 'What this PC needs before taking video orders',
  h3CanonicalRequirementsIntro: 'Install all four on the same Windows PC. The environment check verifies the service identity as a whole. Two real local videos must pass, followed by publication review, device binding and a fresh check at intake.',
  h3CanonicalComfyRequirement: 'ComfyUI and the local H3 service',
  h3CanonicalModelsRequirement: 'The five H3 model roles',
  h3CanonicalPluginsRequirement: 'Plugins required by the workflow',
  h3CanonicalWorkflowRequirement: 'The specified four-step qs_new4 workflow',
  h3CanonicalRequirementUnchecked: 'Not verified',
  h3CanonicalRequirementInspected: 'Service identity checked this time',
  h3CanonicalRequirementTrial: 'Prior local video trials verified',
  h3CanonicalInstallGuide: 'If anything is missing, install and start a supported version on this PC, then select Check environment. There is no verifiable signed installer source yet, so the client does not automatically download models, plugins or workflows.',
  h3CanonicalSupplyGate: 'This setup does not enable intake. Video supply stays closed while the environment is incomplete, trials have not passed or a result is uncertain.',
  h3CanonicalServiceOffline: 'Cannot connect to this PC’s H3 service. Start ComfyUI and the local H3 service, then check again.',
  h3CanonicalIdentityUnverified: 'The model, plugin or four-step workflow identity is unverified. Check the installed version and try the environment check again; the client cannot identify a missing file from this response.',
}
