import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { ADVERTISEMENT_PROOF_BY_CAPABILITY, CAPABILITY_BY_TASK_TYPE, CAPABILITY_REGISTRY_VERSION, DETERMINISM_BY_CAPABILITY, IMPLEMENTATIONS_BY_CAPABILITY, LEGACY_TASK_TYPES_BY_CAPABILITY, PREFERRED_LANDING_BY_CAPABILITY, SEMANTIC_CAPABILITY_NAMES } from '../src/capability-registry.ts'

const REGISTRY_URL = new URL('../../../../contracts/v1/capabilities.registry.json', import.meta.url)
const GENERATED_URL = new URL('../src/capability-registry.ts', import.meta.url)

interface RegistryImpl { impl?: string; package_names?: string[]; aliases?: string[]; role?: string | null }
interface RegistryRow {
  capability: string
  determinism?: string
  advertisement_proof: string
  legacy_task_types?: string[]
  implementations?: RegistryImpl[]
}
const registry = JSON.parse(readFileSync(fileURLToPath(REGISTRY_URL), 'utf8')) as {
  registry_version: string
  capabilities: RegistryRow[]
}

describe('capability registry projection', () => {
  it('is the generated artifact, never a hand-written copy', () => {
    expect(readFileSync(fileURLToPath(GENERATED_URL), 'utf8')).toContain('Generated by scripts/gen-capability-registry.ts')
  })

  it('mirrors registry_version', () => {
    expect(CAPABILITY_REGISTRY_VERSION).toBe(registry.registry_version)
  })

  it('copies every advertisement proof requirement from the registry', () => {
    expect(ADVERTISEMENT_PROOF_BY_CAPABILITY).toEqual(Object.fromEntries(
      registry.capabilities.map(row => [row.capability, row.advertisement_proof]),
    ))
  })

  it('carries exactly the legacy_task_types of contracts/v1/capabilities.registry.json', () => {
    const expected: Record<string, string[]> = {}
    for (const row of registry.capabilities) {
      const types = [...new Set(row.legacy_task_types ?? [])].sort()
      if (types.length > 0) expected[row.capability] = types
    }
    expect(LEGACY_TASK_TYPES_BY_CAPABILITY).toEqual(expected)
    const preferred: Record<string, string> = {}
    for (const row of registry.capabilities) {
      preferred[row.capability] = [...new Set(row.legacy_task_types ?? [])][0] ?? row.capability
    }
    expect(PREFERRED_LANDING_BY_CAPABILITY).toEqual(preferred)
    expect(PREFERRED_LANDING_BY_CAPABILITY['text.transform']).toBe('word_count')
    expect(PREFERRED_LANDING_BY_CAPABILITY['image.generate']).toBe('image.generate')
    // Native legal documents and renderer have explicit semantic capabilities and task landings.
    expect(registry.capabilities).toHaveLength(27)
    expect(Object.keys(LEGACY_TASK_TYPES_BY_CAPABILITY)).toHaveLength(25)
    expect(Object.keys(PREFERRED_LANDING_BY_CAPABILITY)).toHaveLength(27)
    expect([...SEMANTIC_CAPABILITY_NAMES].sort()).toEqual([...registry.capabilities.map(row => row.capability)].sort())
  })

  it('carries exactly the implementations of contracts/v1/capabilities.registry.json', () => {
    const expected: Record<string, { id: string; names: string[]; role: string | null }[]> = {}
    for (const row of [...registry.capabilities].sort((a, b) => a.capability.localeCompare(b.capability))) {
      const impls = []
      for (const impl of row.implementations ?? []) {
        const names = [...new Set([...(impl.package_names ?? []), ...(impl.aliases ?? [])])]
        if (names.length === 0 || typeof impl.impl !== 'string' || impl.impl.trim() === '') continue
        const role = typeof impl.role === 'string' && impl.role.trim() !== '' ? impl.role.trim() : null
        impls.push({ id: impl.impl.trim(), names, role })
      }
      if (impls.length > 0) expected[row.capability] = impls
    }
    expect(IMPLEMENTATIONS_BY_CAPABILITY).toEqual(expected)
  })

  it('copies registry determinism and only marks local generation as random', () => {
    const expected: Record<string, string> = {}
    for (const row of [...registry.capabilities].sort((a, b) => a.capability.localeCompare(b.capability))) {
      if (row.determinism === 'deterministic' || row.determinism === 'random') expected[row.capability] = row.determinism
    }
    expect(DETERMINISM_BY_CAPABILITY).toEqual(expected)
    expect(DETERMINISM_BY_CAPABILITY['media.transcode']).toBe('deterministic')
    expect(DETERMINISM_BY_CAPABILITY['llm.generate.local']).toBe('random')
    expect(DETERMINISM_BY_CAPABILITY['image.generate']).toBe('random')
    expect(DETERMINISM_BY_CAPABILITY['media.compose']).toBe('random')
    expect(DETERMINISM_BY_CAPABILITY['text.transform']).toBe('deterministic')
    expect(Object.values(DETERMINISM_BY_CAPABILITY).filter(value => value === 'random').sort()).toEqual(['random', 'random', 'random', 'random', 'random'])
  })

  it('reverses every semantic name and every legacy task_type onto one capability', () => {
    const expected: Record<string, string> = {}
    for (const row of registry.capabilities) {
      expected[row.capability] = row.capability
      for (const type of row.legacy_task_types ?? []) expected[type] = row.capability
    }
    expect(CAPABILITY_BY_TASK_TYPE).toEqual(expected)
    expect(CAPABILITY_BY_TASK_TYPE.video_compress).toBe('media.transcode')
    expect(CAPABILITY_BY_TASK_TYPE['media.transcode']).toBe('media.transcode')
  })

  it('never lets one platform task_type land on two capabilities', () => {
    const seen = new Map<string, string>()
    for (const [capability, types] of Object.entries(LEGACY_TASK_TYPES_BY_CAPABILITY)) {
      for (const type of types) {
        expect(seen.get(type), `task_type ${type} claimed by ${seen.get(type)} and ${capability}`).toBeUndefined()
        seen.set(type, capability)
      }
    }
  })
})
