import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { TASK_INPUT_PROPERTIES_BY_KIND, TASK_INPUT_REQUIRED_BY_KIND, TASK_SCHEMA_PROPERTY_NAMES } from '../src/task-chain-schema.ts'

const SCHEMA_URL = new URL('../../../../contracts/v1/task.schema.json', import.meta.url)
const GENERATED_URL = new URL('../src/task-chain-schema.ts', import.meta.url)
const TOOLS_URL = new URL('../src/tools.ts', import.meta.url)

const schema = JSON.parse(readFileSync(fileURLToPath(SCHEMA_URL), 'utf8')) as {
  properties: Record<string, { oneOf?: { properties?: Record<string, { const?: string }>; required?: string[] }[] }>
}

describe('task chain schema projection', () => {
  it('is the generated artifact, never a hand-written copy', () => {
    expect(readFileSync(fileURLToPath(GENERATED_URL), 'utf8')).toContain('Generated by scripts/gen-task-chain-schema.ts')
  })

  it('mirrors every closed-root property name including deadline_s', () => {
    expect([...TASK_SCHEMA_PROPERTY_NAMES]).toEqual(Object.keys(schema.properties))
    expect(TASK_SCHEMA_PROPERTY_NAMES).toContain('deadline_s')
  })

  it('mirrors input.oneOf required keys and property names', () => {
    const required: Record<string, string[]> = {}
    const properties: Record<string, string[]> = {}
    const input = schema.properties.input
    if (input === undefined) throw new Error('missing input schema')
    for (const branch of input.oneOf ?? []) {
      const kind = branch.properties?.kind?.const
      if (typeof kind !== 'string') throw new Error('missing kind')
      required[kind] = branch.required ?? []
      properties[kind] = Object.keys(branch.properties ?? {})
    }
    expect(TASK_INPUT_REQUIRED_BY_KIND).toEqual(required)
    expect(TASK_INPUT_PROPERTIES_BY_KIND).toEqual(properties)
  })

  it('does not hand-copy task schema field names into the chain tool', () => {
    const tools = readFileSync(fileURLToPath(TOOLS_URL), 'utf8')
    const start = tools.indexOf("name: 'compute_dispatch_chain'")
    const end = tools.indexOf("name: 'compute_plan_draft'")
    expect(start).toBeGreaterThan(0)
    expect(end).toBeGreaterThan(start)
    const block = tools.slice(start, end)
    expect(block).not.toContain('deadline_s')
    expect(block).not.toContain('deadline_seconds')
    expect(block).not.toContain('task_type')
    expect(block).not.toContain('idempotency_key')
  })
})
