/**
 * Generated by scripts/gen-capability-registry.ts — do not edit by hand; run
 * `pnpm run gen-capability-registry` to regenerate (freshness-gated by
 * `pnpm run verify-capability-registry` in doc-sync).
 *
 * Projection of `contracts/v1/capabilities.registry.json`: the semantic capability
 * vocabulary, the platform `task_type` spellings it records as `legacy_task_types`,
 * the first-listed preferred landing, the reverse `task_type` → capability map, `determinism`,
 * and each implementation's package names, aliases, and `role`.
 * Data only — the registry JSON is the sole source; this module exists because a
 * published package cannot read `contracts/` at runtime.
 */

/** `registry_version` of the projected registry. */
export const CAPABILITY_REGISTRY_VERSION = "1.0"

/** Semantic capability name → platform `task_type` names recorded as its legacy spellings. */
export const LEGACY_TASK_TYPES_BY_CAPABILITY: Readonly<Record<string, readonly string[]>> = {
  "legal.doc.bundle": ["legal_doc_bundle_v1"],
  "audio.extract": ["audio_extract"],
  "audio.transcode": ["audio_transcode"],
  "compute.numeric": ["fft_compute"],
  "doc.pdf.extract": ["pdf_to_text"],
  "doc.pdf.probe": ["pdf_info"],
  "doc.spreadsheet.write": ["excel_export"],
  "image.convert": ["image_convert"],
  "image.probe": ["image_info"],
  "image.thumbnail": ["image_thumbnail"],
  "image.transform": ["image_compress", "image_resize"],
  "llm.generate.local": ["local_llm_chat"],
  "media.compose": ["qianshou_film_media"],
  "media.probe": ["video_info"],
  "media.thumbnail": ["video_thumbnail"],
  "media.transcode": ["video_compress", "video_repurpose"],
  "ml.onnx.infer": ["onnx_infer"],
  "ocr.image": ["pdf_ocr", "rapid_ocr_v1"],
  "render.3d": ["blender_render"],
  "speech.transcribe": ["audio_transcribe_refine", "video_analyze", "whisper_transcribe"],
  "text.transform": ["base64_decode", "json_validate", "text_sort", "word_count"],
  "video.render": ["bar_chart_svg_v1", "video_generate"],
  "vision.caption": ["image_caption"],
  "web.extract": ["crawl_url_extract"],
  "web.fetch": ["crawl_batch_fetch", "crawl_url_fetch"],
}

/** Semantic capability name → first listed `legacy_task_types` name, or the id when it has none. */
export const PREFERRED_LANDING_BY_CAPABILITY: Readonly<Record<string, string>> = {
  "legal.doc.bundle": "legal_doc_bundle_v1",
  "accelerator.gpu": "accelerator.gpu",
  "audio.extract": "audio_extract",
  "audio.transcode": "audio_transcode",
  "compute.numeric": "fft_compute",
  "doc.pdf.extract": "pdf_to_text",
  "doc.pdf.probe": "pdf_info",
  "doc.spreadsheet.write": "excel_export",
  "image.convert": "image_convert",
  "image.generate": "image.generate",
  "image.probe": "image_info",
  "image.thumbnail": "image_thumbnail",
  "image.transform": "image_resize",
  "llm.generate.local": "local_llm_chat",
  "media.compose": "qianshou_film_media",
  "media.probe": "video_info",
  "media.thumbnail": "video_thumbnail",
  "media.transcode": "video_compress",
  "ml.onnx.infer": "onnx_infer",
  "ocr.image": "pdf_ocr",
  "render.3d": "blender_render",
  "speech.transcribe": "whisper_transcribe",
  "text.transform": "word_count",
  "video.render": "bar_chart_svg_v1",
  "vision.caption": "image_caption",
  "web.extract": "crawl_url_extract",
  "web.fetch": "crawl_url_fetch",
}

/** Platform `task_type` or semantic name → owning semantic capability. */
export const CAPABILITY_BY_TASK_TYPE: Readonly<Record<string, string>> = {
  "legal.doc.bundle": "legal.doc.bundle",
  "legal_doc_bundle_v1": "legal.doc.bundle",
  "accelerator.gpu": "accelerator.gpu",
  "audio_extract": "audio.extract",
  "audio_transcode": "audio.transcode",
  "audio_transcribe_refine": "speech.transcribe",
  "audio.extract": "audio.extract",
  "audio.transcode": "audio.transcode",
  "base64_decode": "text.transform",
  "bar_chart_svg_v1": "video.render",
  "video_generate": "video.render",
  "blender_render": "render.3d",
  "compute.numeric": "compute.numeric",
  "crawl_batch_fetch": "web.fetch",
  "crawl_url_extract": "web.extract",
  "crawl_url_fetch": "web.fetch",
  "doc.pdf.extract": "doc.pdf.extract",
  "doc.pdf.probe": "doc.pdf.probe",
  "doc.spreadsheet.write": "doc.spreadsheet.write",
  "excel_export": "doc.spreadsheet.write",
  "fft_compute": "compute.numeric",
  "image_caption": "vision.caption",
  "image_compress": "image.transform",
  "image_convert": "image.convert",
  "image_info": "image.probe",
  "image_resize": "image.transform",
  "image_thumbnail": "image.thumbnail",
  "image.convert": "image.convert",
  "image.generate": "image.generate",
  "image.probe": "image.probe",
  "image.thumbnail": "image.thumbnail",
  "image.transform": "image.transform",
  "json_validate": "text.transform",
  "llm.generate.local": "llm.generate.local",
  "local_llm_chat": "llm.generate.local",
  "media.compose": "media.compose",
  "media.probe": "media.probe",
  "media.thumbnail": "media.thumbnail",
  "media.transcode": "media.transcode",
  "ml.onnx.infer": "ml.onnx.infer",
  "ocr.image": "ocr.image",
  "onnx_infer": "ml.onnx.infer",
  "pdf_info": "doc.pdf.probe",
  "pdf_ocr": "ocr.image",
  "pdf_to_text": "doc.pdf.extract",
  "qianshou_film_media": "media.compose",
  "rapid_ocr_v1": "ocr.image",
  "render.3d": "render.3d",
  "speech.transcribe": "speech.transcribe",
  "text_sort": "text.transform",
  "text.transform": "text.transform",
  "video_analyze": "speech.transcribe",
  "video_compress": "media.transcode",
  "video_info": "media.probe",
  "video_repurpose": "media.transcode",
  "video.render": "video.render",
  "video_thumbnail": "media.thumbnail",
  "vision.caption": "vision.caption",
  "web.extract": "web.extract",
  "web.fetch": "web.fetch",
  "whisper_transcribe": "speech.transcribe",
  "word_count": "text.transform",
}

/** One advertised implementation: registry impl id, package names plus aliases, and optional `role`. */
export interface CapabilityImplementationAd {
  /** Registry `implementations[].impl` id; this is what a node may put in `provides[].impl.runtime`. */
  readonly id: string
  /** Package names and aliases copied from the registry implementation row. */
  readonly names: readonly string[]
  /** Registry `role`. Same role is OR; different roles are AND; `null` means unroled (all OR). */
  readonly role: string | null
}

/** Semantic capability name → implementations that satisfy it. */
export const IMPLEMENTATIONS_BY_CAPABILITY: Readonly<Record<string, readonly CapabilityImplementationAd[]>> = {
  "audio.extract": [{ id: "ffmpeg", names: ["ffmpeg"], role: null }],
  "audio.transcode": [{ id: "ffmpeg", names: ["ffmpeg"], role: null }],
  "compute.numeric": [{ id: "numpy", names: ["numpy"], role: null }],
  "doc.pdf.extract": [{ id: "pymupdf", names: ["pymupdf", "fitz"], role: null }, { id: "pdfplumber", names: ["pdfplumber"], role: null }],
  "doc.pdf.probe": [{ id: "pymupdf", names: ["pymupdf", "fitz"], role: null }],
  "doc.spreadsheet.write": [{ id: "openpyxl", names: ["openpyxl"], role: null }],
  "image.convert": [{ id: "pillow", names: ["pillow", "PIL"], role: null }],
  "image.probe": [{ id: "pillow", names: ["pillow", "PIL"], role: null }],
  "image.thumbnail": [{ id: "pillow", names: ["pillow", "PIL"], role: null }],
  "image.transform": [{ id: "pillow", names: ["pillow", "PIL"], role: null }],
  "llm.generate.local": [{ id: "local_llm", names: ["local_llm", "ollama"], role: null }],
  "media.probe": [{ id: "ffmpeg", names: ["ffmpeg"], role: null }],
  "media.thumbnail": [{ id: "ffmpeg", names: ["ffmpeg"], role: null }],
  "media.transcode": [{ id: "ffmpeg", names: ["ffmpeg"], role: null }],
  "ml.onnx.infer": [{ id: "onnxruntime", names: ["onnxruntime"], role: null }],
  "ocr.image": [{ id: "paddleocr", names: ["paddleocr"], role: null }, { id: "rapidocr", names: ["rapidocr", "rapidocr_onnxruntime"], role: null }, { id: "pytesseract", names: ["pytesseract", "tesseract"], role: null }],
  "render.3d": [{ id: "blender", names: ["blender", "bpy"], role: null }],
  "speech.transcribe": [{ id: "whisper", names: ["whisper"], role: null }, { id: "faster_whisper", names: ["faster_whisper", "faster-whisper"], role: null }],
  "vision.caption": [{ id: "moondream2", names: ["moondream2"], role: null }],
  "web.extract": [{ id: "selectolax", names: ["selectolax"], role: "html_parser" }, { id: "readability", names: ["readability", "readability-lxml"], role: "content_extractor" }],
  "web.fetch": [{ id: "requests", names: ["requests"], role: "http_client" }, { id: "selectolax", names: ["selectolax"], role: "html_parser" }],
}

/** Every semantic capability name in the registry, including rows with no package advertisement. */
export const SEMANTIC_CAPABILITY_NAMES: readonly string[] = ["accelerator.gpu", "audio.extract", "audio.transcode", "compute.numeric", "doc.pdf.extract", "doc.pdf.probe", "doc.spreadsheet.write", "image.convert", "image.generate", "image.probe", "image.thumbnail", "image.transform", "legal.doc.bundle", "llm.generate.local", "media.compose", "media.probe", "media.thumbnail", "media.transcode", "ml.onnx.infer", "ocr.image", "render.3d", "speech.transcribe", "text.transform", "video.render", "vision.caption", "web.extract", "web.fetch"]

/** Closed cache/retry classification copied from the registry. Missing is not deterministic. */
export type CapabilityDeterminism = 'deterministic' | 'random'

/** Semantic capability name → registry `determinism`. Cache only admits `deterministic`. */
export const DETERMINISM_BY_CAPABILITY: Readonly<Record<string, CapabilityDeterminism>> = {
  "legal.doc.bundle": "random",
  "accelerator.gpu": "deterministic",
  "audio.extract": "deterministic",
  "audio.transcode": "deterministic",
  "compute.numeric": "deterministic",
  "doc.pdf.extract": "deterministic",
  "doc.pdf.probe": "deterministic",
  "doc.spreadsheet.write": "deterministic",
  "image.convert": "deterministic",
  "image.generate": "random",
  "image.probe": "deterministic",
  "image.thumbnail": "deterministic",
  "image.transform": "deterministic",
  "llm.generate.local": "random",
  "media.compose": "random",
  "media.probe": "deterministic",
  "media.thumbnail": "deterministic",
  "media.transcode": "deterministic",
  "ml.onnx.infer": "deterministic",
  "ocr.image": "deterministic",
  "render.3d": "deterministic",
  "speech.transcribe": "deterministic",
  "text.transform": "deterministic",
  "video.render": "random",
  "vision.caption": "deterministic",
  "web.extract": "deterministic",
  "web.fetch": "deterministic",
}

/** Proof required before software-name matching may advertise a capability. */
export type CapabilityAdvertisementProof = 'software-probe' | 'executor-self-test' | 'host-binding'

/** Registry classification; software probes do not establish executor availability. */
export const ADVERTISEMENT_PROOF_BY_CAPABILITY: Readonly<Record<string, CapabilityAdvertisementProof>> = {
  'legal.doc.bundle': 'host-binding',
  'accelerator.gpu': 'host-binding',
  'audio.extract': 'software-probe',
  'audio.transcode': 'software-probe',
  'compute.numeric': 'software-probe',
  'doc.pdf.extract': 'software-probe',
  'doc.pdf.probe': 'software-probe',
  'doc.spreadsheet.write': 'software-probe',
  'image.convert': 'software-probe',
  'image.generate': 'executor-self-test',
  'image.probe': 'software-probe',
  'image.thumbnail': 'software-probe',
  'image.transform': 'software-probe',
  'llm.generate.local': 'executor-self-test',
  'media.compose': 'host-binding',
  'media.probe': 'software-probe',
  'media.thumbnail': 'software-probe',
  'media.transcode': 'software-probe',
  'ml.onnx.infer': 'executor-self-test',
  'ocr.image': 'software-probe',
  'render.3d': 'software-probe',
  'speech.transcribe': 'executor-self-test',
  'text.transform': 'host-binding',
  'video.render': 'host-binding',
  'vision.caption': 'executor-self-test',
  'web.extract': 'software-probe',
  'web.fetch': 'software-probe',
}
