/**
 * Generated by scripts/gen-task-chain-schema.ts — do not edit by hand; run
 * `pnpm run gen-task-chain-schema` to regenerate (freshness-gated by
 * `pnpm run verify-task-chain-schema`).
 *
 * Projection of `contracts/v1/task.schema.json`: property names and the per-kind required keys of `input`.
 * Data only — the JSON Schema is the sole source; this module exists because a
 * published package cannot read `contracts/` at runtime.
 */

/** Closed-root property names of `qianshou/task/v1`. */
export const TASK_SCHEMA_PROPERTY_NAMES: readonly string[] = ["contract", "task_id", "task_type", "input", "requires", "budget", "deadline_s", "idempotency_key", "pin", "fan_out", "join", "anchor"]

/** `input.oneOf` required keys keyed by `kind`. */
export const TASK_INPUT_REQUIRED_BY_KIND: Readonly<Record<string, readonly string[]>> = {
  "inline": ["kind", "value"],
  "ref": ["kind", "uri"],
  "stream": ["kind", "stream_id"],
}

/** `input.oneOf` property names keyed by `kind`, including optional keys. */
export const TASK_INPUT_PROPERTIES_BY_KIND: Readonly<Record<string, readonly string[]>> = {
  "inline": ["kind", "value"],
  "ref": ["kind", "uri", "sha256"],
  "stream": ["kind", "stream_id"],
}
