<template><div class="qs-auth"><header class="qs-auth-header"><BrandMark/><a href="/#/">返回官网 ↗</a></header><main class="qs-auth-main"><aside class="qs-auth-story"><p class="qs-eyebrow">ONE ECOSYSTEM. YOUR POSSIBILITIES.</p><h1>连接你的工作，<br>连接更多<span>可能。</span></h1><p>从一个账号开始，进入千手生态。<br>应用、设备、任务与结果，各就其位。</p><div class="auth-orbit" aria-hidden="true"><i></i><i></i><i></i><b>千手<br><small>QIANSHOU</small></b><span class="orbit-label l1">APPLICATION</span><span class="orbit-label l2">COMPUTE</span><span class="orbit-label l3">CREATION</span></div><div class="auth-principles"><span>独立应用</span><span>分布式算力</span><span>统一工作空间</span></div></aside><section class="qs-auth-form" :aria-label="title"><div class="auth-form-head"><p class="qs-eyebrow">{{eyebrow}}</p><h2>{{title}}</h2><p>{{description}}</p></div><slot/></section></main><footer class="qs-auth-footer"><span>© 2026 千手生态 · QIANSHOU</span><div><a href="/#/terms">用户服务协议</a><a href="/#/privacy">隐私政策</a></div></footer></div></template>
<script lang="ts">
import { defineComponent } from 'vue'
import BrandMark from './BrandMark.vue'
export default defineComponent({
  components: { BrandMark },
  props: {
    title: { type: String, required: true },
    description: { type: String, required: true },
    eyebrow: { type: String, default: 'WELCOME TO QIANSHOU' },
  },
})
</script>
<style scoped>.qs-auth{min-height:100vh;background:var(--qs-bg);display:flex;flex-direction:column}.qs-auth-header{width:min(1320px,calc(100% - 80px));margin:auto;padding:26px 0;display:flex;justify-content:space-between;align-items:center}.qs-auth-header>a:last-child{font-size:12px;color:var(--qs-muted);text-decoration:none}.qs-auth-main{width:min(1160px,calc(100% - 80px));margin:auto;display:grid;grid-template-columns:1.25fr 1fr;gap:110px;align-items:center;padding:55px 0 70px;flex:1}.qs-auth-story{position:relative}.qs-auth-story h1{font-size:44px;font-weight:500;line-height:1.6;letter-spacing:-1.8px;margin:23px 0}.qs-auth-story h1 span{color:var(--qs-accent)}.qs-auth-story>p:nth-of-type(2){font-size:14px;line-height:1.9;color:var(--qs-muted)}.auth-orbit{position:relative;width:310px;height:200px;margin:30px auto;background:radial-gradient(ellipse,#8ebfff3f,transparent 70%);display:grid;place-items:center;perspective:500px}.auth-orbit i{position:absolute;inset:20px 10px;border:1px solid #92b7e74f;border-radius:50%;transform:rotate(-25deg)}.auth-orbit i:nth-child(2){transform:rotate(25deg)}.auth-orbit i:nth-child(3){transform:rotate(90deg);inset:35px 15px}.auth-orbit b{font-weight:500;text-align:center;font-size:22px;color:var(--qs-accent);letter-spacing:3px;z-index:1}.auth-orbit small{font:8px/1.8 monospace;letter-spacing:2px}.orbit-label{position:absolute;font:8px monospace;color:#527eae;letter-spacing:1px;background:#f6f8fb;padding:6px}.l1{left:0;top:40px}.l2{bottom:10px;left:100px}.l3{right:-15px;top:80px}.auth-principles{display:flex;gap:24px;font-size:10px;color:var(--qs-muted);letter-spacing:1px}.auth-principles span:before{content:'＋';color:var(--qs-accent);margin-right:8px}.qs-auth-form{padding:34px;border:1px solid var(--qs-line);border-radius:16px;background:var(--qs-panel);box-shadow:0 20px 80px #234b7310}.auth-form-head{margin-bottom:27px}.auth-form-head h2{font-size:28px;font-weight:500;letter-spacing:-.7px;margin:14px 0}.auth-form-head>p:last-child{font-size:12px;color:var(--qs-muted);line-height:1.8}.qs-auth-footer{width:min(1320px,calc(100% - 80px));margin:auto;padding:23px 0;border-top:1px solid var(--qs-line);display:flex;justify-content:space-between;gap:20px;font-size:10px;color:var(--qs-muted)}.qs-auth-footer div{display:flex;gap:22px}.qs-auth-footer a{text-decoration:none}@media(max-width:950px){.qs-auth-main{gap:40px}.qs-auth-story h1{font-size:32px}.auth-principles{gap:10px;font-size:9px}.auth-orbit{width:260px}}@media(max-width:720px){.qs-auth-main{display:block;width:min(470px,calc(100% - 40px));padding:25px 0 45px}.qs-auth-story{display:none}.qs-auth-header,.qs-auth-footer{width:calc(100% - 40px)}.qs-auth-header{padding:22px 0}.qs-auth-form{padding:27px 22px}.qs-auth-footer{font-size:9px;flex-wrap:wrap;gap:12px}}
</style>
