import { createHash } from 'node:crypto'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ComputeCapabilityId, ComputeTaskId } from '@deepseek-ai/dsh-compute-core'
import type { ComputeResidentAttemptExecution } from '@deepseek-ai/dsh-compute-core/resident'
import { createArtifactOrderConsumer, type ArtifactOrderAdapter } from '../src/artifact-order.ts'

const roots: string[] = []
afterEach(async () => Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))))

async function workspace() {
  const path = await mkdtemp(join(tmpdir(), 'qianshou-artifact-order-'))
  roots.push(path)
  return { path, outputs: [], close: async () => undefined }
}

const digest = `sha256:${'a'.repeat(64)}`
function execution(input = '{"kind":"bar_chart_svg_v1"}', format = 'mp4'): ComputeResidentAttemptExecution {
  const taskId = ComputeTaskId('workload-1.shard-1')
  return {
    task: {
      version: 'qianshou.task.v1', taskId, capabilityId: ComputeCapabilityId('bar_chart_svg_v1'),
      capabilityVersion: '1.0.0', inputRefs: [],
      parameters: { taskType: 'bar_chart_svg_v1', inlineInput: input, runtime: 'node', taskParams: { output_format: format } },
      deadlineAt: '2026-09-25T23:00:00.000Z', maxOutputBytes: 1_000_000, idempotencyKey: 'b'.repeat(64),
    },
    attempt: {
      taskId, attempt: 1, leaseId: 'lease-1', leaseExpiresAt: '2026-09-25T23:00:00.000Z',
      idempotencyKey: 'b'.repeat(64), envelopeFingerprint: 'c'.repeat(64), capabilityId: 'bar_chart_svg_v1',
      capabilityVersion: '1.0.0', capabilityPluginDigest: 'a'.repeat(64),
    },
    signal: new AbortController().signal,
    reportProgress: async () => undefined,
    source: { open: async () => new ReadableStream() }, dataSource: {},
  }
}

function adapter(run: ArtifactOrderAdapter['run']): ArtifactOrderAdapter {
  return { taskType: 'bar_chart_svg_v1', inputKind: 'inline', outputKind: 'artifact_ref',
    contractVersion: 'v1', artifactDigest: digest, packageDigest: digest,
    outputFormats: ['gif', 'mp4'], run }
}

describe('explicit artifact order consumer', () => {
  it.each(['v2', 'v3', '', null, 42] as const)('rejects an unknown or unbranded contract version %s before execution', (version) => {
    const run = vi.fn(async () => { throw new Error('Invalid adapter must not run') })
    const upload = vi.fn(async () => { throw new Error('Invalid adapter must not upload') })
    const remember = vi.fn()
    const candidate = adapter(run)
    Reflect.set(candidate, 'contractVersion', version)
    expect(() => createArtifactOrderConsumer(candidate, { upload, remember }))
      .toThrow('COMPUTE_ARTIFACT_ADAPTER_INVALID')
    expect(run).not.toHaveBeenCalled()
    expect(upload).not.toHaveBeenCalled()
    expect(remember).not.toHaveBeenCalled()
  })

  it('checks generated bytes, uploads once, then remembers only the returned reference', async () => {
    const dir = await workspace()
    const bytes = Buffer.from('0000ftyp-test-video')
    const upload = vi.fn(async (_taskId, _attempt, input) => ({
      schema: 'artifact.v1' as const, object_key: 'v8/server-issued/result.mp4',
      object_version_id: 'oss-version-1', filename: input.filename,
      size_bytes: input.bytes.length, content_type: input.contentType,
      sha256: createHash('sha256').update(input.bytes).digest('hex'),
      result_id: 'result-1', shard_id: 'shard-1', workload_id: 'workload-1', account_id: 7,
    }))
    const remember = vi.fn()
    const run = vi.fn(async ({ workspacePath }) => {
      const path = join(workspacePath, 'result.mp4')
      await writeFile(path, bytes)
      return { path, filename: 'result.mp4', contentType: 'video/mp4' as const }
    })
    const consumer = createArtifactOrderConsumer(adapter(run), { upload, remember })
    const receipt = await consumer.consume({ execution: execution(), workspace: dir, signal: new AbortController().signal })
    expect(run).toHaveBeenCalledWith(expect.objectContaining({ recipeJson: '{"kind":"bar_chart_svg_v1"}', outputFormat: 'mp4' }))
    expect(upload).toHaveBeenCalledWith('workload-1.shard-1', 1,
      expect.objectContaining({ filename: 'result.mp4', contentType: 'video/mp4', bytes }), expect.any(AbortSignal))
    expect(remember).toHaveBeenCalledOnce()
    expect(receipt.outputs).toEqual([{ name: 'result.mp4', bytes: bytes.length,
      sha256: createHash('sha256').update(bytes).digest('hex') }])
  })

  it('rejects undeclared format, script-shaped inputs and output paths outside the workspace before upload', async () => {
    const upload = vi.fn()
    const remember = vi.fn()
    const runner = vi.fn(async () => ({ path: '/etc/hosts', filename: 'result.mp4', contentType: 'video/mp4' as const }))
    const consumer = createArtifactOrderConsumer(adapter(runner), { upload, remember })
    const dir = await workspace()
    await expect(consumer.consume({ execution: execution('{}'), workspace: dir, signal: new AbortController().signal }))
      .rejects.toMatchObject({ code: 'COMPUTE_ARTIFACT_PARAMETERS_INVALID' })
    await expect(consumer.consume({ execution: execution('{"kind":"bar_chart_svg_v1"}', 'exe'), workspace: dir,
      signal: new AbortController().signal })).rejects.toMatchObject({ code: 'COMPUTE_ARTIFACT_PARAMETERS_INVALID' })
    expect(runner).not.toHaveBeenCalled()
    await expect(consumer.consume({ execution: execution(), workspace: dir, signal: new AbortController().signal }))
      .rejects.toMatchObject({ code: 'COMPUTE_ARTIFACT_OUTPUT_INVALID' })
    expect(upload).not.toHaveBeenCalled()
    expect(remember).not.toHaveBeenCalled()
  })

  it('does not remember a media upload with no immutable object version', async () => {
    const dir = await workspace()
    const bytes = Buffer.from('0000ftyp-test-video')
    const run = vi.fn(async ({ workspacePath }) => {
      const path = join(workspacePath, 'result.mp4')
      await writeFile(path, bytes)
      return { path, filename: 'result.mp4', contentType: 'video/mp4' as const }
    })
    const upload = vi.fn(async () => ({
      schema: 'artifact.v1' as const, object_key: 'v8/server-issued/result.mp4',
      object_version_id: 'null', filename: 'result.mp4', size_bytes: bytes.length,
      content_type: 'video/mp4' as const,
      sha256: createHash('sha256').update(bytes).digest('hex'),
      result_id: 'result-1', shard_id: 'shard-1', workload_id: 'workload-1', account_id: 7,
    }))
    const remember = vi.fn()
    const consumer = createArtifactOrderConsumer(adapter(run), { upload, remember })
    await expect(consumer.consume({
      execution: execution(), workspace: dir, signal: new AbortController().signal,
    })).rejects.toMatchObject({ code: 'COMPUTE_ARTIFACT_UPLOAD_MISMATCH' })
    expect(remember).not.toHaveBeenCalled()
  })
})
