import { describe, expect, it } from 'vitest'
import { canonicalH3Endpoint, H3CanonicalProtocolError, parseH3CanonicalIdentity,
  parseH3CanonicalJob, parseH3CanonicalPostExpected, verifyH3CanonicalMedia,
  type H3CanonicalJobExpectation } from '../src/h3-canonical-protocol.ts'

// Generated by ten extracted, actual canonical Python JSON constructors, without importing or starting the package.
// recipe_identity.py 806b3f37a62b96a99210effd7fb63514fc8e135e1fd2a6222e0709ff9f380d71
// workbench_node.py 638f0bbf376813e22c9ba62b239d04e0043810650c796ff8a422c25314da54bd
// Synthetic model/class/encoder digests and media below do not demonstrate a rendered video or enrolled device.
const wire: { identity: unknown; expected: unknown; jobs: Record<string, unknown>; mediaBase64: string } = {
  'identity': {
    'schemaVersion': 'qs.h3.recipe-identity.canonical-vnext',
    'workflow': 'qs_new4',
    'recipeVersion': '1.0.0-rc.1',
    'graphTemplateSha256': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
    'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'modelSetSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'sourceManifestSha256': '937a6aea58c9e4b8a269d7e1abb4c8da5b528c50d68267fe2c186ac09ee0dc3b',
    'classOriginSha256': 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
    'graphSha256': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'runtimeAbi': 'qs.h3.canonical.qs_new4.vnext',
    'weightSha256ByRole': {
      'audioVae': '1111111111111111111111111111111111111111111111111111111111111111',
      'clip': '2222222222222222222222222222222222222222222222222222222222222222',
      'lora': '3333333333333333333333333333333333333333333333333333333333333333',
      'unet': '4444444444444444444444444444444444444444444444444444444444444444',
      'videoVae': '5555555555555555555555555555555555555555555555555555555555555555',
    },
  },
  'expected': {
    'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
    'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  },
  'jobs': {
    'queued': {
      'job_id': 'qa-canonical-job',
      'id': 'qa-canonical-job',
      'phase': 'queued',
      'status': 'queued',
      'pct': 0,
      'percent': 0,
      'done': false,
      'failed': false,
      'cancelled': false,
      'error': null,
      'video_url': null,
      'file_url': null,
      'elapsed_sec': 1,
      'progress': {
        'percent': 0,
        'value': 0,
        'max': 0,
        'node': null,
        'phase': 'queued',
        'message': null,
      },
      'fed': {
        'version': '0.1.0-canonical.20260927',
      },
      'recipe_identity': {
        'schemaVersion': 'qs.h3.job-identity.canonical-vnext',
        'expected': {
          'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
          'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        },
        'actual': null,
        'attested': false,
      },
    },
    'running': {
      'job_id': 'qa-canonical-job',
      'id': 'qa-canonical-job',
      'phase': 'running',
      'status': 'running',
      'pct': 0,
      'percent': 0,
      'done': false,
      'failed': false,
      'cancelled': false,
      'error': null,
      'video_url': null,
      'file_url': null,
      'elapsed_sec': 1,
      'progress': {
        'percent': 0,
        'value': 0,
        'max': 0,
        'node': null,
        'phase': 'running',
        'message': null,
      },
      'fed': {
        'version': '0.1.0-canonical.20260927',
      },
      'recipe_identity': {
        'schemaVersion': 'qs.h3.job-identity.canonical-vnext',
        'expected': {
          'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
          'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        },
        'actual': null,
        'attested': false,
      },
    },
    'failed': {
      'job_id': 'qa-canonical-job',
      'id': 'qa-canonical-job',
      'phase': 'failed',
      'status': 'failed',
      'pct': 0,
      'percent': 0,
      'done': false,
      'failed': true,
      'cancelled': false,
      'error': null,
      'video_url': null,
      'file_url': null,
      'elapsed_sec': 1,
      'progress': {
        'percent': 0,
        'value': 0,
        'max': 0,
        'node': null,
        'phase': 'failed',
        'message': null,
      },
      'fed': {
        'version': '0.1.0-canonical.20260927',
      },
      'recipe_identity': {
        'schemaVersion': 'qs.h3.job-identity.canonical-vnext',
        'expected': {
          'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
          'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        },
        'actual': null,
        'attested': false,
      },
    },
    'cancelled': {
      'job_id': 'qa-canonical-job',
      'id': 'qa-canonical-job',
      'phase': 'cancelled',
      'status': 'cancelled',
      'pct': 0,
      'percent': 0,
      'done': false,
      'failed': false,
      'cancelled': true,
      'error': null,
      'video_url': null,
      'file_url': null,
      'elapsed_sec': 1,
      'progress': {
        'percent': 0,
        'value': 0,
        'max': 0,
        'node': null,
        'phase': 'cancelled',
        'message': null,
      },
      'fed': {
        'version': '0.1.0-canonical.20260927',
      },
      'recipe_identity': {
        'schemaVersion': 'qs.h3.job-identity.canonical-vnext',
        'expected': {
          'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
          'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        },
        'actual': null,
        'attested': false,
      },
    },
    'done': {
      'job_id': 'qa-canonical-job',
      'id': 'qa-canonical-job',
      'phase': 'done',
      'status': 'done',
      'pct': 0,
      'percent': 0,
      'done': true,
      'failed': false,
      'cancelled': false,
      'error': null,
      'video_url': 'http://127.0.0.1:8790/v1/jobs/qa-canonical-job/video',
      'file_url': 'http://127.0.0.1:8790/v1/jobs/qa-canonical-job/video',
      'elapsed_sec': 1,
      'progress': {
        'percent': 0,
        'value': 0,
        'max': 0,
        'node': null,
        'phase': 'done',
        'message': null,
      },
      'fed': {
        'version': '0.1.0-canonical.20260927',
      },
      'recipe_identity': {
        'schemaVersion': 'qs.h3.job-identity.canonical-vnext',
        'expected': {
          'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
          'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        },
        'actual': {
          'executionRecipeSha256': 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
          'modelSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
          'modelSetSha256': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
          'sourceManifestSha256': '937a6aea58c9e4b8a269d7e1abb4c8da5b528c50d68267fe2c186ac09ee0dc3b',
          'classOriginSha256': 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
          'deliverySha256': '4dd06600aa088c2032d238aa62d53204a88df2d2bb428ddc15645e9e4ce1c97f',
          'deliverySize': 63,
          'comfyFfmpegSha256': 'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
          'deliveryFfmpegSha256': 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
        },
        'attested': true,
      },
      'comfy_model_load_generation_sha256': 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
    },
  },
  'mediaBase64': 'AAAAGGZ0eXBpc29tY2Fub25pY2FsIHByb3RvY29sIGZpeHR1cmUsIG5vdCBhIHJlYWwgcmVuZGVyZWQgTVA0',
}

function row(value: unknown): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new Error('fixture object required')
  return value as Record<string, unknown>
}
function job(state = 'done'): Record<string, unknown> { return row(structuredClone(wire.jobs[state])) }
function final(value: Record<string, unknown>): Record<string, unknown> { return row(row(value.recipe_identity).actual) }
const identity = parseH3CanonicalIdentity(wire.identity)
const expected: H3CanonicalJobExpectation = { jobId: 'qa-canonical-job', adapterBase: 'http://127.0.0.1:8790',
  identity, comfyFfmpegSha256: 'd'.repeat(64), deliveryFfmpegSha256: 'e'.repeat(64) }
function completed() {
  const parsed = parseH3CanonicalJob(wire.jobs.done, expected)
  if (parsed.state !== 'completed') throw new Error('fixture must complete')
  return parsed
}

describe('canonical actual identity and submission expectations', () => {
  it('reads the actual independent identity, freezes its copy and projects only two POST digests', () => {
    expect(Object.keys(identity)).toHaveLength(12)
    expect(identity.sourceManifestSha256).toBe('937a6aea58c9e4b8a269d7e1abb4c8da5b528c50d68267fe2c186ac09ee0dc3b')
    expect(Object.isFrozen(identity)).toBe(true)
    expect(Object.isFrozen(identity.weightSha256ByRole)).toBe(true)
    expect(parseH3CanonicalPostExpected(wire.expected)).toEqual({
      executionRecipeSha256: identity.executionRecipeSha256, modelSha256: identity.modelSha256 })
  })
  it.each([
    ['schemaVersion', 'qs.h3.recipe-identity.v2'], ['runtimeAbi', 'qianshou.order-runtime.native-h3.v2'],
    ['workflow', 'other_workflow'], ['recipeVersion', 'unknown'], ['modelSetSha256', '0'.repeat(64)],
    ['graphTemplateSha256', '0'.repeat(64)], ['sourceManifestSha256', 'not-a-sha'],
    ['classOriginSha256', 'C'.repeat(64)], ['executionRecipeSha256', '1'.repeat(64)],
  ])('rejects incompatible or inconsistent identity %s', (key, value) => {
    const input = row(structuredClone(wire.identity)); input[key] = value
    expect(() => parseH3CanonicalIdentity(input)).toThrow(H3CanonicalProtocolError)
  })
  it('rejects missing or extra identity keys and missing, extra or malformed model roles', () => {
    const input = row(structuredClone(wire.identity)); delete input.runtimeAbi
    expect(() => parseH3CanonicalIdentity(input)).toThrow()
    expect(() => parseH3CanonicalIdentity({ ...row(wire.identity), localConfigSha256: 'a'.repeat(64) })).toThrow()
    const badWeights = row(structuredClone(wire.identity))
    delete row(badWeights.weightSha256ByRole).lora
    expect(() => parseH3CanonicalIdentity(badWeights)).toThrow()
    row(badWeights.weightSha256ByRole).lora = 'invalid'
    expect(() => parseH3CanonicalIdentity(badWeights)).toThrow()
    row(badWeights.weightSha256ByRole).lora = 'a'.repeat(64)
    row(badWeights.weightSha256ByRole).newRole = 'a'.repeat(64)
    expect(() => parseH3CanonicalIdentity(badWeights)).toThrow()
  })
  it('recomputes the production public recipe rather than accepting a copied execution digest', () => {
    const input = row(structuredClone(wire.identity)); input.classOriginSha256 = 'a'.repeat(64)
    expect(() => parseH3CanonicalIdentity(input)).toThrow()
  })
  it('bounds complete multibyte JSON and reports no private data on encoding failures', () => {
    const input = { ...row(wire.identity), privatePath: '私'.repeat(24_000) }
    expect(() => parseH3CanonicalIdentity(input)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    const cycle: Record<string, unknown> = {}; cycle.self = cycle
    expect(() => parseH3CanonicalIdentity(cycle)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    expect(() => parseH3CanonicalIdentity(null)).toThrow()
    expect(() => parseH3CanonicalIdentity([])).toThrow()
  })
  it('refuses V2/input fields and requires both raw lower-case POST hashes', () => {
    expect(() => parseH3CanonicalPostExpected({ ...row(wire.expected), firstFrameSha256: 'c'.repeat(64) })).toThrow()
    expect(() => parseH3CanonicalPostExpected({ executionRecipeSha256: identity.executionRecipeSha256 })).toThrow()
    expect(() => parseH3CanonicalPostExpected({ ...row(wire.expected), modelSha256: `sha256:${identity.modelSha256}` })).toThrow()
  })
})

describe('fixed loopback routes', () => {
  it('constructs only the actual canonical route family, including IPv6', () => {
    expect(canonicalH3Endpoint(expected.adapterBase, { kind: 'identity' }).href)
      .toBe('http://127.0.0.1:8790/v1/recipes/qs_new4/identity')
    expect(canonicalH3Endpoint(expected.adapterBase, { kind: 'jobs' }).pathname).toBe('/v1/jobs')
    expect(canonicalH3Endpoint(expected.adapterBase, { kind: 'poll', jobId: expected.jobId }).pathname)
      .toBe('/v1/jobs/qa-canonical-job')
    expect(canonicalH3Endpoint('http://[::1]:8790/', { kind: 'video', jobId: expected.jobId }).href)
      .toBe('http://[::1]:8790/v1/jobs/qa-canonical-job/video')
  })
  it.each(['https://127.0.0.1:8790', 'http://example.invalid', 'http://localhost:8790',
    'http://127.0.0.1:8790/other', 'http://owner:secret@127.0.0.1:8790',
    'http://127.0.0.1:8790/?path=private', 'http://127.0.0.1:8790/#private', 'invalid'])
  ('rejects unsafe origin %s', (base) => {
    expect(() => canonicalH3Endpoint(base, { kind: 'identity' })).toThrow(H3CanonicalProtocolError)
  })
  it.each(['../other', 'a/b', 'a%2fb', 'a\\b', '中文', '', '.'])('rejects job traversal %s', (id) => {
    expect(() => canonicalH3Endpoint(expected.adapterBase, { kind: 'video', jobId: id })).toThrow()
  })
})

describe('actual canonical job packets', () => {
  it.each(['queued', 'running', 'failed', 'cancelled'])('retains %s without projecting paths or allowing a retry', (state) => {
    const input = job(state); input.error = '/private/owner/secret-path'; input.feedback = { urls: { video: 'https://untrusted.invalid/private' } }
    expect(parseH3CanonicalJob(input, expected)).toEqual({ state, jobId: expected.jobId })
    expect(JSON.stringify(parseH3CanonicalJob(input, expected))).not.toContain('private')
  })
  it('accepts only the completed source, class, model, encoder and generation witness', () => {
    expect(completed()).toEqual({ state: 'completed', jobId: expected.jobId,
      sha256: final(job()).deliverySha256, bytes: Buffer.from(wire.mediaBase64, 'base64').byteLength,
      modelLoadGenerationSha256: 'f'.repeat(64) })
    const input = job(); input.video_url = '/v1/jobs/qa-canonical-job/video'; input.file_url = input.video_url
    expect(parseH3CanonicalJob(input, expected).state).toBe('completed')
  })
  it.each(['executionRecipeSha256', 'modelSha256', 'modelSetSha256', 'sourceManifestSha256',
    'classOriginSha256', 'comfyFfmpegSha256', 'deliveryFfmpegSha256'])('rejects a changed completed %s', (key) => {
    const input = job(); final(input)[key] = '0'.repeat(64)
    expect(() => parseH3CanonicalJob(input, expected)).toThrow()
  })
  it.each([0, -1, 16 * 1024 * 1024 + 1, 1.5, Number.MAX_SAFE_INTEGER + 1, '64'])
  ('rejects invalid delivered size %s', (size) => {
    const input = job(); final(input).deliverySize = size
    expect(() => parseH3CanonicalJob(input, expected)).toThrow()
  })
  it('refuses a different job, schema, expected tuple or unverified completion', () => {
    const input = job(); input.id = 'different-job'
    expect(() => parseH3CanonicalJob(input, expected)).toThrow()
    const old = job(); row(old.recipe_identity).schemaVersion = 'qs.h3.job-identity.v2'
    expect(() => parseH3CanonicalJob(old, expected)).toThrow()
    const wrong = job(); row(row(wrong.recipe_identity).expected).modelSha256 = '0'.repeat(64)
    expect(() => parseH3CanonicalJob(wrong, expected)).toThrow()
    const unattested = job(); row(unattested.recipe_identity).attested = false
    expect(() => parseH3CanonicalJob(unattested, expected)).toThrow()
    const pending = job('running'); row(pending.recipe_identity).actual = final(job())
    expect(() => parseH3CanonicalJob(pending, expected)).toThrow()
  })
  it('does not follow server-provided URLs and rejects foreign origins, jobs or query strings', () => {
    for (const url of ['https://external.invalid/file', 'http://127.0.0.1:9999/v1/jobs/qa-canonical-job/video',
      'http://127.0.0.1:8790/v1/jobs/other/video', '/v1/jobs/qa-canonical-job/video?private=1']) {
      const input = job(); input.video_url = url
      expect(() => parseH3CanonicalJob(input, expected)).toThrow()
    }
  })
  it('requires exact nested fields, finite consistent states and a bounded whole packet', () => {
    const extra = job(); final(extra).path = '/private/output.mp4'
    expect(() => parseH3CanonicalJob(extra, expected)).toThrow()
    const missing = job(); delete missing.comfy_model_load_generation_sha256
    expect(() => parseH3CanonicalJob(missing, expected)).toThrow()
    const contradiction = job('running'); contradiction.done = true
    expect(() => parseH3CanonicalJob(contradiction, expected)).toThrow()
    const unsupported = job('running'); unsupported.status = 'unknown'
    expect(() => parseH3CanonicalJob(unsupported, expected)).toThrow()
    expect(() => parseH3CanonicalJob({ ...job(), localPath: '/private' }, expected)).toThrow()
    expect(() => parseH3CanonicalJob({ ...job(), recent_events: '私'.repeat(24_000) }, expected)).toThrow()
  })
})

describe('bounded receipt media', () => {
  it('checks actual receipt bytes and returns a separate copy without pretending to ffprobe a render', () => {
    const bytes = Buffer.from(wire.mediaBase64, 'base64')
    const verified = verifyH3CanonicalMedia(bytes, completed())
    expect(verified.equals(bytes)).toBe(true)
    bytes.fill(0)
    expect(verified.subarray(4, 8).toString()).toBe('ftyp')
  })
  it('rejects replacement, non-MP4, short, oversized and size-inconsistent bytes', () => {
    const bytes = Buffer.from(wire.mediaBase64, 'base64'); bytes[12] = 0
    expect(() => verifyH3CanonicalMedia(bytes, completed())).toThrow()
    const nonMp4 = Buffer.from(wire.mediaBase64, 'base64'); nonMp4.write('bad!', 4)
    expect(() => verifyH3CanonicalMedia(nonMp4, completed())).toThrow()
    expect(() => verifyH3CanonicalMedia(new Uint8Array(7), completed())).toThrow()
    expect(() => verifyH3CanonicalMedia(new Uint8Array(16 * 1024 * 1024 + 1), completed())).toThrow()
    expect(() => verifyH3CanonicalMedia(Buffer.from(wire.mediaBase64, 'base64'), { ...completed(), bytes: 1 })).toThrow()
  })
})
