import { createHash } from 'node:crypto'
import { once } from 'node:events'
import { createServer, type IncomingHttpHeaders, type IncomingMessage, type Server, type ServerResponse } from 'node:http'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { canonicalH3Endpoint, parseH3CanonicalIdentity, verifyH3CanonicalMedia } from '../src/h3-canonical-protocol.ts'
import { parseH3OwnerRuntimeIdentity, parseH3WitnessedJob, type H3WitnessedJobExpectation } from '../src/h3-owner-witness.ts'
import { readH3OwnerRuntimeIdentity, readH3WitnessedJob, readH3WitnessedMedia } from '../src/h3-canonical-transport.ts'

// Public recipe from the existing actual stage1 Python constructor fixture. Owner measurements are synthetic.
// Its owner self-digest was independently generated by Python hashlib + sorted UTF-8 no-space json.dumps.
// The new Windows wire is only UI-reported; these tests do not verify its source, processes or a rendered MP4.
const publicPacket = {
  schemaVersion: 'qs.h3.recipe-identity.canonical-vnext', workflow: 'qs_new4', recipeVersion: '1.0.0-rc.1',
  graphTemplateSha256: 'a'.repeat(64), graphSha256: 'a'.repeat(64),
  executionRecipeSha256: 'a7b929ee140c10e20eb8f1a50deb32592dc47853946f71bca23bbbf6be720660',
  modelSha256: 'b'.repeat(64), modelSetSha256: 'b'.repeat(64),
  sourceManifestSha256: '937a6aea58c9e4b8a269d7e1abb4c8da5b528c50d68267fe2c186ac09ee0dc3b',
  classOriginSha256: 'c'.repeat(64), runtimeAbi: 'qs.h3.canonical.qs_new4.vnext',
  weightSha256ByRole: { audioVae: '1'.repeat(64), clip: '2'.repeat(64), lora: '3'.repeat(64),
    unet: '4'.repeat(64), videoVae: '5'.repeat(64) },
}
const identity = parseH3CanonicalIdentity(publicPacket)
const SELF_DIGEST = 'b04ca6239f9ab87f0401d0ea90e648b88abf8d02bab13e2404fff7876c62fddb'
const media = Buffer.from('0000ftyp stage4 CPU media fixture; not a generated video')
const sha = (bytes: Uint8Array | string): string => createHash('sha256').update(bytes).digest('hex')
const options = { timeoutMs: 2_000 }

function measured(): Record<string, unknown> {
  return { schemaVersion: 'qs.h3.owner-runtime-identity.v1', ownerConfigDigest: '1'.repeat(64),
    apiProcessWitnessSha256: '2'.repeat(64), comfyProcessWitnessSha256: '3'.repeat(64), queueAdmissionGuardVersion: 1,
    sourceManifestSha256: identity.sourceManifestSha256, classOriginSha256: identity.classOriginSha256,
    comfyFfmpegSha256: 'd'.repeat(64), deliveryFfmpegSha256: 'e'.repeat(64) }
}
function ownerPacket(): Record<string, unknown> { return { ...measured(), ownerRuntimeWitnessSha256: SELF_DIGEST } }
function resigned(packet: Record<string, unknown>): Record<string, unknown> {
  const { ownerRuntimeWitnessSha256: _own, ...fields } = packet
  return { ...fields, ownerRuntimeWitnessSha256: sha(JSON.stringify(fields, Object.keys(fields).sort())) }
}
function row(value: unknown): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new Error('invalid owned fixture row')
  return value as Record<string, unknown>
}
function expected(base = 'http://127.0.0.1:8790'): H3WitnessedJobExpectation {
  return { adapterBase: base, jobId: 'owner-witness-job', identity,
    comfyFfmpegSha256: 'd'.repeat(64), deliveryFfmpegSha256: 'e'.repeat(64),
    owner: parseH3OwnerRuntimeIdentity(ownerPacket(), identity) }
}
function job(state: 'queued' | 'running' | 'failed' | 'cancelled' | 'done' = 'done'): Record<string, unknown> {
  const done = state === 'done'; const path = '/v1/jobs/owner-witness-job/video'
  return { job_id: 'owner-witness-job', id: 'owner-witness-job', status: state, phase: state,
    done, failed: state === 'failed', cancelled: state === 'cancelled', error: 'synthetic private diagnostic',
    video_url: done ? path : null, file_url: done ? path : null,
    recipe_identity: { schemaVersion: 'qs.h3.job-identity.canonical-vnext',
      expected: { executionRecipeSha256: identity.executionRecipeSha256, modelSha256: identity.modelSha256 },
      ownerRuntimeWitnessSha256: SELF_DIGEST, attested: done,
      actual: done ? { executionRecipeSha256: identity.executionRecipeSha256, modelSha256: identity.modelSha256,
        modelSetSha256: identity.modelSetSha256, sourceManifestSha256: identity.sourceManifestSha256,
        classOriginSha256: identity.classOriginSha256, deliverySha256: sha(media), deliverySize: media.length,
        comfyFfmpegSha256: 'd'.repeat(64), deliveryFfmpegSha256: 'e'.repeat(64), ownerRuntimeWitnessSha256: SELF_DIGEST } : null },
    ...(done ? { comfy_model_load_generation_sha256: 'f'.repeat(64) } : {}) }
}

describe('exact owner-process witness packets', () => {
  it('accepts independently computed sorted UTF-8 self-digest, excludes its own field and copies/freeze measurements', () => {
    const packet = ownerPacket(); const parsed = parseH3OwnerRuntimeIdentity(packet, identity)
    expect(Object.keys(parsed)).toHaveLength(10); expect(Object.isFrozen(parsed)).toBe(true)
    expect(parsed.ownerRuntimeWitnessSha256).toBe(SELF_DIGEST)
    expect(sha(JSON.stringify(measured(), Object.keys(measured()).sort()))).toBe(SELF_DIGEST)
    expect(sha(JSON.stringify(measured()))).not.toBe(SELF_DIGEST)
    packet.ownerConfigDigest = 'a'.repeat(64)
    expect(parsed.ownerConfigDigest).toBe('1'.repeat(64))
    const wrong = ownerPacket()
    wrong.ownerRuntimeWitnessSha256 = sha(JSON.stringify(wrong, Object.keys(wrong).sort()))
    expect(() => parseH3OwnerRuntimeIdentity(wrong, identity)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each(Object.keys(ownerPacket()))('rejects missing exact owner field %s', (key) => {
    const { [key]: _removed, ...packet } = ownerPacket()
    expect(() => parseH3OwnerRuntimeIdentity(packet, identity)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each([null, [], 1, 'private-body', { ...ownerPacket(), privatePath: 'synthetic/private/config' }])(
    'rejects non-object or additional owner fields: %j', (packet) => {
      expect(() => parseH3OwnerRuntimeIdentity(packet, identity)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it.each([0, 2, '1', true, 1.5, Number.NaN])('requires integer guard version exactly 1: %j', (version) => {
    expect(() => parseH3OwnerRuntimeIdentity(resigned({ ...ownerPacket(), queueAdmissionGuardVersion: version }), identity))
      .toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each(['ownerConfigDigest', 'apiProcessWitnessSha256', 'comfyProcessWitnessSha256', 'sourceManifestSha256',
    'classOriginSha256', 'comfyFfmpegSha256', 'deliveryFfmpegSha256', 'ownerRuntimeWitnessSha256'])(
    'rejects uppercase/non-hash bytes in %s even when other fields are valid', (key) => {
      const packet = resigned({ ...ownerPacket(), [key]: 'A'.repeat(64) })
      if (key === 'ownerRuntimeWitnessSha256') packet[key] = 'A'.repeat(64)
      expect(() => parseH3OwnerRuntimeIdentity(packet, identity)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it.each(['a'.repeat(63), 'sha256:' + 'a'.repeat(64), '猫'.repeat(64), null, 3])(
    'rejects malformed owner hash format despite a recomputed self-digest: %j', (hash) => {
      expect(() => parseH3OwnerRuntimeIdentity(resigned({ ...ownerPacket(), ownerConfigDigest: hash }), identity))
        .toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it.each(['sourceManifestSha256', 'classOriginSha256'])(
    'requires independently parsed public software %s, not only a valid owner self-digest', (key) => {
      expect(() => parseH3OwnerRuntimeIdentity(resigned({ ...ownerPacket(), [key]: '9'.repeat(64) }), identity))
        .toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it('refuses changed process/config measurements under a stale digest and accepts only a freshly measured distinct witness', () => {
    const packet = { ...ownerPacket(), apiProcessWitnessSha256: '9'.repeat(64) }
    expect(() => parseH3OwnerRuntimeIdentity(packet, identity)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    const next = parseH3OwnerRuntimeIdentity(resigned(packet), identity)
    expect(next.ownerRuntimeWitnessSha256).not.toBe(SELF_DIGEST)
    expect(next.apiProcessWitnessSha256).toBe('9'.repeat(64))
  })

  it('rejects older owner schema and a self-digest computed with spaces instead of the fixed encoding', () => {
    expect(() => parseH3OwnerRuntimeIdentity(resigned({ ...ownerPacket(), schemaVersion: 'qs.h3.owner-runtime-identity.v0' }), identity))
      .toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    const packet = ownerPacket()
    packet.ownerRuntimeWitnessSha256 = sha(JSON.stringify(measured(), Object.keys(measured()).sort(), 2))
    expect(() => parseH3OwnerRuntimeIdentity(packet, identity)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })
})

describe('same-submission owner witness on polling and completed output', () => {
  it.each(['queued', 'running', 'failed', 'cancelled', 'done'] as const)(
    'retains the exact same owner witness on finite %s state, with no private server text', (state) => {
      const parsed = parseH3WitnessedJob(job(state), expected())
      expect(parsed.state).toBe(state === 'done' ? 'completed' : state)
      expect(parsed.ownerRuntimeWitnessSha256).toBe(SELF_DIGEST)
      expect(Object.isFrozen(parsed)).toBe(true)
      expect(parsed).not.toHaveProperty('error'); expect(parsed).not.toHaveProperty('video_url')
    })

  it('accepts completed exact ten-field actual and preserves measured media metadata independently', () => {
    const parsed = parseH3WitnessedJob(job(), expected())
    if (parsed.state !== 'completed') throw new Error('missing terminal fixture')
    expect(parsed).toMatchObject({ jobId: 'owner-witness-job', sha256: sha(media), bytes: media.length,
      modelLoadGenerationSha256: 'f'.repeat(64), ownerRuntimeWitnessSha256: SELF_DIGEST })
    const copy = verifyH3CanonicalMedia(media, parsed)
    expect(copy.equals(media)).toBe(true); copy[0] = 99; expect(media[0]).toBe(48)
  })

  it.each(['receipt', 'actual', 'captured-owner'] as const)('rejects a mixed witness from %s', (boundary) => {
    const packet = job(); let expectation = expected()
    if (boundary === 'receipt') row(packet.recipe_identity).ownerRuntimeWitnessSha256 = '9'.repeat(64)
    else if (boundary === 'actual') row(row(packet.recipe_identity).actual).ownerRuntimeWitnessSha256 = '9'.repeat(64)
    else expectation = { ...expectation, owner: parseH3OwnerRuntimeIdentity(resigned({ ...ownerPacket(),
      apiProcessWitnessSha256: '9'.repeat(64) }), identity) }
    expect(() => parseH3WitnessedJob(packet, expectation)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each(['queued', 'done'] as const)('refuses legacy four-field receipt on the new %s reader', (state) => {
    const packet = job(state); delete row(packet.recipe_identity).ownerRuntimeWitnessSha256
    if (state === 'done') delete row(row(packet.recipe_identity).actual).ownerRuntimeWitnessSha256
    expect(() => parseH3WitnessedJob(packet, expected())).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it('refuses legacy nine-field actual even when its new five-field receipt claims the captured witness', () => {
    const packet = job(); delete row(row(packet.recipe_identity).actual).ownerRuntimeWitnessSha256
    expect(() => parseH3WitnessedJob(packet, expected())).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each(['executionRecipeSha256', 'modelSha256', 'modelSetSha256', 'sourceManifestSha256', 'classOriginSha256',
    'comfyFfmpegSha256', 'deliveryFfmpegSha256'])(
    'refuses completed wrong measured %s under a valid owner witness', (key) => {
      const packet = job(); row(row(packet.recipe_identity).actual)[key] = '9'.repeat(64)
      expect(() => parseH3WitnessedJob(packet, expected())).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it.each(['comfyFfmpegSha256', 'deliveryFfmpegSha256'] as const)(
    'refuses caller encoder expectation %s differing from the captured owner measurements', (key) => {
      expect(() => parseH3WitnessedJob(job(), { ...expected(), [key]: '9'.repeat(64) }))
        .toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it.each([0, -1, 1.5, 16 * 1024 * 1024 + 1, '64'])('refuses unbounded/non-integer completed media size: %j', (size) => {
    const packet = job(); row(row(packet.recipe_identity).actual).deliverySize = size
    expect(() => parseH3WitnessedJob(packet, expected())).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each(['job_id', 'id', 'done', 'attested', 'status', 'echoed-model', 'extra-actual'])(
    'refuses inconsistent same-job completion: %s', (key) => {
      const packet = job()
      if (key === 'done') packet.done = false
      else if (key === 'attested') row(packet.recipe_identity).attested = false
      else if (key === 'status') packet.status = 'unknown'
      else if (key === 'echoed-model') row(row(packet.recipe_identity).expected).modelSha256 = '9'.repeat(64)
      else if (key === 'extra-actual') row(row(packet.recipe_identity).actual).privatePath = 'synthetic/private/video'
      else packet[key] = 'another-job'
      expect(() => parseH3WitnessedJob(packet, expected())).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it.each(['../secret', '%2e%2e', 'a/b', 'x?token=synthetic', 'localhost-job/'])('refuses caller job traversal: %s', (id) => {
    expect(() => parseH3WitnessedJob(job(), { ...expected(), jobId: id })).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })

  it.each(['http://example.invalid/private.mp4', '/v1/jobs/another-job/video', '/v1/jobs/owner-witness-job/video?x=1'])(
    'refuses a media path differing from the fixed same-job endpoint: %s', (path) => {
      const packet = job(); packet.video_url = path
      expect(() => parseH3WitnessedJob(packet, expected())).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
    })

  it('rejects valid-length tampered media under an otherwise valid captured-witness completion', () => {
    const parsed = parseH3WitnessedJob(job(), expected())
    if (parsed.state !== 'completed') throw new Error('missing terminal fixture')
    const changed = Buffer.from(media); changed[changed.length - 1] = 33
    expect(() => verifyH3CanonicalMedia(changed, parsed)).toThrow('H3_CANONICAL_PROTOCOL_INVALID')
  })
})

const servers: Server[] = []
afterEach(async () => {
  vi.unstubAllEnvs()
  await Promise.all(servers.splice(0).map(async (server) => {
    server.closeAllConnections()
    await new Promise<void>((resolve, reject) => server.close((error) => { if (error) reject(error); else resolve() }))
  }))
})
interface ObservedRequest { method: string | undefined; path: string | undefined; headers: IncomingHttpHeaders; bytes: number }
async function serve(handler: (request: IncomingMessage, response: ServerResponse) => void) {
  const requests: ObservedRequest[] = []
  const server = createServer((request, response) => {
    let bytes = 0
    request.on('data', (part: Buffer) => { bytes += part.length })
    request.on('end', () => {
      requests.push({ method: request.method, path: request.url, headers: request.headers, bytes })
      handler(request, response)
    })
  })
  servers.push(server); server.listen(0, '127.0.0.1'); await once(server, 'listening')
  const address = server.address()
  if (!address || typeof address === 'string') throw new Error('fixture listener unavailable')
  return { base: `http://127.0.0.1:${address.port}`, requests }
}
function json(response: ServerResponse, packet: unknown): void {
  response.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' })
  response.end(JSON.stringify(packet))
}

describe('witnessed fixed loopback reads', () => {
  it('uses three isolated direct GETs owner→same-job→verified media, with no POST/Origin/auth/custom witness header/retry', async () => {
    const server = await serve((request, response) => {
      if (request.url === '/v1/owner-runtime/identity') json(response, ownerPacket())
      else if (request.url === '/v1/jobs/owner-witness-job') json(response, job())
      else if (request.url === '/v1/jobs/owner-witness-job/video') {
        response.writeHead(200, { 'content-type': 'video/mp4' }); response.end(media)
      } else { response.writeHead(404); response.end() }
    })
    vi.stubEnv('HTTP_PROXY', 'http://127.0.0.1:1'); vi.stubEnv('ALL_PROXY', 'http://127.0.0.1:1')
    const owner = await readH3OwnerRuntimeIdentity(server.base, identity, options)
    const expectation = { ...expected(server.base + '/'), owner }
    const completed = await readH3WitnessedJob(expectation, options)
    if (completed.state !== 'completed') throw new Error('missing HTTP terminal fixture')
    const copy = await readH3WitnessedMedia(expectation, completed, options)
    expect(copy.equals(media)).toBe(true); copy[0] = 99; expect(media[0]).toBe(48)
    expect(completed.adapterOrigin).toBe(new URL(server.base).origin)
    expect(server.requests.map(value => value.path)).toEqual([
      '/v1/owner-runtime/identity', '/v1/jobs/owner-witness-job', '/v1/jobs/owner-witness-job/video',
    ])
    for (const request of server.requests) {
      expect(request.method).toBe('GET'); expect(request.bytes).toBe(0)
      expect(Object.keys(request.headers).sort()).toEqual(['accept', 'accept-encoding', 'connection', 'host'])
      expect(request.headers['accept-encoding']).toBe('identity')
    }
  })

  it.each(['owner', 'legacy-poll'] as const)('rejects bad %s without retry and exposes only the finite error', async (boundary) => {
    const server = await serve((_request, response) => {
      if (boundary === 'owner') json(response, { ...ownerPacket(), ownerRuntimeWitnessSha256: '0'.repeat(64) })
      else { const packet = job(); delete row(packet.recipe_identity).ownerRuntimeWitnessSha256; json(response, packet) }
    })
    const result = boundary === 'owner' ? readH3OwnerRuntimeIdentity(server.base, identity, options)
      : readH3WitnessedJob(expected(server.base), options)
    await expect(result).rejects.toMatchObject({ code: 'H3_CANONICAL_PROTOCOL_INVALID', message: 'H3_CANONICAL_PROTOCOL_INVALID' })
    expect(server.requests).toHaveLength(1); expect(server.requests[0]?.method).toBe('GET')
  })

  it('never follows redirects from the owner route and never calls the redirect target', async () => {
    const target = await serve((_request, response) => { json(response, ownerPacket()) })
    const server = await serve((_request, response) => {
      response.writeHead(302, { location: target.base + '/v1/owner-runtime/identity', 'content-type': 'application/json' })
      response.end('{}')
    })
    await expect(readH3OwnerRuntimeIdentity(server.base, identity, options)).rejects.toMatchObject({ code: 'H3_CANONICAL_RESPONSE_INVALID' })
    expect(server.requests).toHaveLength(1); expect(target.requests).toHaveLength(0)
  })

  it.each(['owner', 'base', 'encoder', 'job', 'public-model'] as const)(
    'rejects a captured completed media %s mismatch before any HTTP request', async (boundary) => {
      const server = await serve((_request, response) => { response.writeHead(200, { 'content-type': 'video/mp4' }); response.end(media) })
      const captured = expected(server.base)
      const completed = parseH3WitnessedJob(job(), captured)
      if (completed.state !== 'completed') throw new Error('missing terminal fixture')
      let current = captured
      if (boundary === 'owner') current = { ...captured, owner: parseH3OwnerRuntimeIdentity(resigned({ ...ownerPacket(),
        apiProcessWitnessSha256: '9'.repeat(64) }), identity) }
      else if (boundary === 'base') current = { ...captured, adapterBase: 'http://127.0.0.1:1' }
      else if (boundary === 'encoder') current = { ...captured, comfyFfmpegSha256: '9'.repeat(64) }
      else if (boundary === 'public-model') current = { ...captured, identity: parseH3CanonicalIdentity({ ...publicPacket,
        modelSha256: '9'.repeat(64), modelSetSha256: '9'.repeat(64),
        // Independent Python sorted-json recipe digest for this different model tuple.
        executionRecipeSha256: 'bab05a051fc5edf98bf60719e83d9860e9205b286b580fdd6271b91e466ad229' }) }
      else current = { ...captured, jobId: 'another-job' }
      await expect(readH3WitnessedMedia(current, completed, options)).rejects.toMatchObject({ code: 'H3_CANONICAL_REQUEST_INVALID' })
      expect(server.requests).toHaveLength(0)
    })

  it.each(['queued', 'running', 'failed', 'cancelled'] as const)(
    'refuses a genuine parsed %s job on the media reader before any HTTP request', async (state) => {
      const server = await serve((_request, response) => { response.writeHead(200, { 'content-type': 'video/mp4' }); response.end(media) })
      const captured = expected(server.base)
      const unfinished = parseH3WitnessedJob(job(state), captured)
      await expect(readH3WitnessedMedia(captured, unfinished, options)).rejects.toMatchObject({ code: 'H3_CANONICAL_REQUEST_INVALID' })
      expect(server.requests).toHaveLength(0)
    })

  it.each(['http://localhost:8790', 'https://127.0.0.1:8790', 'http://127.0.0.1:8790/private',
    'http://127.0.0.1:8790/?x=1', 'http://user:synthetic@127.0.0.1:8790'])(
    'rejects nonliteral or decorated origins before reading owner data: %s', async (base) => {
      await expect(readH3OwnerRuntimeIdentity(base, identity, options)).rejects.toMatchObject({ code: 'H3_CANONICAL_PROTOCOL_INVALID' })
    })

  it('constructs only the fixed owner GET route for a literal loopback origin', () => {
    expect(canonicalH3Endpoint('http://127.0.0.1:8790', { kind: 'owner-identity' }).href)
      .toBe('http://127.0.0.1:8790/v1/owner-runtime/identity')
  })
})
