/** Locale-owned product copy for the dedicated phone shell. */

export const zh = {
  brand: '千手 AI',
  tagline: '一群AI，为你而来',
  hello: '你好，',
  askLead: '我可以为你',
  askAccent: '做什么？',
  // 这里原本是「连接上千个AI智能体」——那是假的规模。真实能力只有两条：这台手机自己对话、
  // 或把任务派给电脑执行。副标题只说这两件事。
  subtitle: '手机自己对话，电脑替你干活。',
  tryAlso: '你还可以试试',
  shuffle: '换一批',
  composerPlaceholder: '发消息，输入 @ 选择专家...',
  webSearch: '联网搜索',
  deepThink: '深度思考',
  // 这两个开关目前没有后端：`send()` 里只有「联网搜索」有分支。开关打开时必须当场说清，
  // 否则用户会以为它生效了——这是最坏的一种假交互。
  deepThinkNoEffect: '深度思考暂时不改变结果：当前接口没有可调的推理档位。',
  moreToolsNoEffect: '更多工具还没接上：手机端现在只有对话与联网搜索。',
  tools: '工具',
  fileUpload: '文件上传',
  imageGen: '图像生成',
  moreTools: '更多工具',
  tabChat: '对话',
  tabAgents: '市场',
  tabDiscover: '发现',
  tabTasks: '任务',
  tabMe: '我的',
  menuTitle: '菜单',
  newChat: '新对话',
  connectPc: '连接电脑',
  settings: '设置',
  close: '关闭',
  send: '发送',
  back: '返回',
  queued: '已排队，等待电脑上的当前任务结束后开始',
  localOnly: '本页先把指令记在手机上。接到电脑会话后才会真正执行。',
  agentsTitle: '专家',
  agentsIntro: '选择一个员工，让它在你的电脑上完成工作。',
  discoverTitle: '发现',
  discoverIntro: '官方与第三方能力，安装后由电脑执行。',
  tasksTitle: '任务',
  tasksEmpty: '还没有进行中的任务。从对话发出的工作会显示在这里。',
  meTitle: '我的',
  // 账号空态：**没有账号时不许显示昵称、会员、ID**。这里以前写的是「经验值/会员/UID」那套，
  // 现在界面上的身份只有两个来源——本地未登录，或将来接上的真实账号。
  meSignedOut: '未登录',
  meSignedOutHint: '登录后可用你的算力账号',
  meSignIn: '登录 / 注册',
  meAccountSoon: '登录即将开放',
  meBalancePrefix: '余额 ',
  meHint: '这台手机自己就能对话（用你填的模型）；电脑连着时，还可以把活儿交给电脑执行。',
  mePc: '尚未连接电脑',
  pcOnline: '电脑在线',
  pcOffline: '电脑离线',
  pcUnauthorized: '未连接到这台电脑',
  pcUnavailable: '电脑会话暂时不可用',
  pcChipOnline: '已连接',
  pcChipOffline: '离线',
  pcChipUnauthorized: '未授权',
  pcChipUnavailable: '未连接',
  pcChipConnecting: '连接中',
  pcNoSession: '请先在电脑上打开一个对话',
  pcConnecting: '正在连接电脑',
  settingsPcTitle: '电脑连接',
  settingsPcHint: '手机是电脑千手的窗口。用 dsh web 打印的带 token 的地址打开本页后，cookie 会留在这个浏览器里。',
  settingsReconnect: '重新连接',
  welcomeTitle: '已接上你自己的模型',
  welcomeLine1: '密钥、模型、对话记录都只留在这台设备上。',
  welcomeLine2: '电脑连着时，也可以把这条派给电脑执行。',
  welcomeHint: '在下面输入一句话开始。',
  followLabel: '接着问',
  deliveryReceived: '电脑已接收',
  deliveryUncertain: '未能确认是否送到电脑',
  deliveryRejected: '电脑未接收',
  cardPlanTitle: '帮我写一份方案',
  cardPlanDesc: '市场分析、商业计划、...',
  cardDataTitle: '分析一份数据',
  cardDataDesc: '图表、趋势、结论',
  cardImageTitle: '生成一张图片',
  cardImageDesc: '海报、插画、设计图',
  cardCodeTitle: '帮我写一段代码',
  cardCodeDesc: '支持多种编程语言',
  agentCeo: '总设计师',
  agentCeoDesc: '理解目标、拆任务、汇总结果',
  agentEng: '工程',
  agentEngDesc: '改代码、跑测试、看终端',
  agentQa: '质量安全',
  agentQaDesc: '验收、权限与风险检查',
  discoverPlugins: '插件市场',
  discoverSkills: '技能',
  discoverWorkflows: '工作流',
  statusQueued: '排队中',
  statusRunning: '进行中',
  statusWaiting: '待确认',
  // —— 接入真实模型后新增的文案：设置页、发送状态、会话历史 ——
  modelPickerTitle: '选择模型',
  modelNotConfigured: '未配置模型',
  modelPickerEmpty: '还没有可选模型。去「我的 → 模型设置」填写服务地址与模型名。',
  settingsTitle: '模型设置',
  settingsProvider: '服务商',
  settingsBaseUrl: '服务地址',
  settingsBaseUrlHint: 'OpenAI 兼容的根地址，通常以 /v1 结尾。',
  settingsApiKey: 'API Key',
  settingsApiKeyPlaceholder: '粘贴你的密钥',
  settingsShow: '显示',
  settingsHide: '隐藏',
  settingsModel: '模型',
  settingsModelHint: '填服务商文档里的模型名，例如 gpt-4o-mini。',
  settingsSave: '保存',
  settingsSaved: '已保存在这台设备上',
  settingsTest: '测试连接',
  settingsTesting: '测试中…',
  settingsTestOk: '连接成功，可以用。',
  settingsPrivacy: '密钥只存在这台设备上，不会上传到任何服务器。但 localStorage 不是加密存储：能拿到这台设备的人就能读到它。',
  settingsBack: '返回',
  settingsStorageFailed: '本机存储写入失败（可能是隐私模式或空间已满）。这次设置没有保存。',
  sessionsEmpty: '这台手机上还没有对话。发一条就有了。',
  sessionsHint: '本机对话在本地模型上继续；发到电脑的指令是一条独立记录，只记投递状态，执行与结果都在电脑端。',
  history: '历史对话',
  stop: '停止',
  streaming: '正在回复…',
  // —— 分阶段状态：把"等第一个字"与"正在吐字"分开，而不是从点击到结束只有一句话 ——
  thinking: '思考中',
  idle: '就绪',
  aborted: '已停止',
  testNeedEndpoint: '先填服务地址再测试。',
  testNeedKey: '先填 API Key 再测试。',
  testTimeout: '测试超时，服务商没有在 15 秒内响应。',
  // —— 两种能力合并后新增的文案：模式条、模式选择、双份历史、空态 ——
  modePickerTitle: '这条消息交给谁',
  modeLocal: '这台手机回答',
  modeRemote: '派给电脑执行',
  modeBarLocalOnly: '电脑不可用，这台手机自己回答',
  modeBarLocalReady: '这台手机回答；也可以派给电脑',
  modeBarRemote: '这条会派给电脑执行',
  modeUsePc: '改用电脑',
  modeUseLocal: '改用手机',
  modePcFellBack: '电脑暂时不可用，这条改由手机回答',
  modeRemoteHint: '在下方选择「派给电脑执行」即可。',
  settingsLocalTitle: '这台手机自己的模型',
  settingsLocalHint: '请求从这台设备直连你的服务商，不经过千手的服务器，也不需要电脑开机。',
  settingsPcOptional: '电脑连接是可选的：连不上时手机照常对话，不会丢任何记录。',
  remoteRecordHint: '下面这些是发到电脑的指令，只显示投递状态；执行与结果都在电脑端。',
  sessionsLocalTitle: '这台手机的对话',
  sessionsPcTitle: '发到电脑的指令',
  sessionsRecordsEmpty: '还没有发到电脑的指令。把模式切成「派给电脑执行」后，发送的记录会出现在这里。',
  meModeLabel: '这台手机怎么工作',
  liveJobsNone: '实时任务数据还没有接上，这里暂时是空的。',
  liveJobsEmpty: '实时任务数据尚未接入',
  // —— 首页四张卡片：文案原来挂在 data.ts 的中文字符串上（`t[tile.title]`），
  //    本地化表里没有对应键，界面拿到的是 undefined。改为按 tile.id 取本地化文案。 ——
  tileCreateTitle: '创建专家',
  tileCreateDesc: '让一群AI为你工作',
  tileRunTitle: '任务运行',
  tileRunDesc: '分配 · 执行 · 监控',
  tileFlowTitle: '工作流',
  tileFlowDesc: '自动化你的业务',
  tileDataTitle: '数据分析',
  tileDataDesc: '从数据中发现价值',
  // —— 联网搜索：开关打开后这条会怎么走，必须在发送前就说清楚 ——
  searchBarRemote: '这条会由电脑联网搜索后回答',
  searchBarPhone: '电脑不在线；这台手机用你自己的密钥联网搜索后回答',
  searchBarOffline: '电脑不在线，无法联网搜索；这条会由手机上的模型直接回答，可能不含最新信息',
  searchBarUnsupported: '当前服务商不支持联网搜索；这条会由手机上的模型直接回答，可能不含最新信息',
  // 订阅通道只做对话，没有联网搜索：这一条说"没有"，不是"暂时没接上"。
  searchBarSubscription: '订阅通道不带联网搜索；这条会直接回答，不含最新信息',
  // —— 订阅通道：走哪条路、还剩多少点数，都要说成可核对的事实 ——
  routeTitle: '对话通道',
  routeNowSubscription: '现在走订阅通道（额度由账号里的订阅扣，不用填密钥）',
  routeNowByok: '现在走你自己的密钥（请求从这台设备直连你的服务商）',
  creditLabel: '剩余',
  creditUnit: '点',
  creditReading: '正在读额度…',
  creditUnknown: '额度未知',
  // —— 搜索过程中的中间状态：搜索与整理分开说，而不是笼统的"正在回复" ——
  searchSearching: '正在搜索…',
  searchReading: '正在整理…',
  searchSources: '这次回答引用了 {n} 个联网来源',

}

export type Copy = typeof zh

export const en: Copy = {
  brand: 'Qianshou AI',
  tagline: 'A team of AIs, for you',
  hello: 'Hello,',
  askLead: 'What can I do ',
  askAccent: 'for you?',
  subtitle: 'Chat on the phone; let the PC do the work.',
  tryAlso: 'You can also try',
  shuffle: 'Refresh',
  composerPlaceholder: 'Message, or type @ to pick an agent...',
  webSearch: 'Web search',
  deepThink: 'Deep think',
  deepThinkNoEffect: 'Deep think changes nothing yet: the API exposes no reasoning-effort setting.',
  moreToolsNoEffect: 'More tools are not wired up: the phone has chat and web search only.',
  tools: 'Tools',
  fileUpload: 'Upload',
  imageGen: 'Image',
  moreTools: 'More tools',
  tabChat: 'Chat',
  tabAgents: 'Agents',
  tabDiscover: 'Discover',
  tabTasks: 'Tasks',
  tabMe: 'Me',
  menuTitle: 'Menu',
  newChat: 'New chat',
  connectPc: 'Connect PC',
  settings: 'Settings',
  close: 'Close',
  send: 'Send',
  back: 'Back',
  queued: 'Queued. It waits until the current PC task finishes.',
  localOnly: 'This page stores the instruction on the phone first. It runs only after the PC session admits it.',
  agentsTitle: 'Agents',
  agentsIntro: 'Pick an employee to do the work on your computer.',
  discoverTitle: 'Discover',
  discoverIntro: 'Official and third-party capabilities. The PC executes them after install.',
  tasksTitle: 'Tasks',
  tasksEmpty: 'No tasks yet. Work you send from Chat appears here.',
  meTitle: 'Me',
  meSignedOut: 'Not signed in',
  meSignedOutHint: 'Sign in to use your compute account',
  meSignIn: 'Sign in / Register',
  meAccountSoon: 'Sign-in is coming soon',
  meBalancePrefix: 'Balance ',
  meHint: 'This phone talks on its own with the model you configured; while the PC is connected you can also hand work to the PC.',
  mePc: 'No PC connected',
  pcOnline: 'PC online',
  pcOffline: 'PC offline',
  pcUnauthorized: 'Not connected to this PC',
  pcUnavailable: 'The PC session is unavailable',
  pcChipOnline: 'Connected',
  pcChipOffline: 'Offline',
  pcChipUnauthorized: 'Unauthorized',
  pcChipUnavailable: 'Not connected',
  pcChipConnecting: 'Connecting',
  pcNoSession: 'Open a conversation on the PC first',
  pcConnecting: 'Connecting to the PC',
  settingsPcTitle: 'PC connection',
  settingsPcHint: 'The phone is a window onto PC Qianshou. Open this page with the token URL printed by dsh web so the browser cookie stays on this origin.',
  settingsReconnect: 'Reconnect',
  welcomeTitle: 'Connected to your own model',
  welcomeLine1: 'The key, the model, and the conversation stay on this device.',
  welcomeLine2: 'While the PC is connected you can also hand this message to the PC.',
  welcomeHint: 'Type a sentence below to start.',
  followLabel: 'Ask next',
  deliveryReceived: 'Received by the PC',
  deliveryUncertain: 'Could not confirm delivery to the PC',
  deliveryRejected: 'The PC did not receive this',
  cardPlanTitle: 'Write a proposal',
  cardPlanDesc: 'Market research, business plan, ...',
  cardDataTitle: 'Analyze some data',
  cardDataDesc: 'Charts, trends, conclusions',
  cardImageTitle: 'Generate an image',
  cardImageDesc: 'Posters, illustration, design',
  cardCodeTitle: 'Write some code',
  cardCodeDesc: 'Many programming languages',
  agentCeo: 'Chief designer',
  agentCeoDesc: 'Reads the goal, splits work, returns results',
  agentEng: 'Engineering',
  agentEngDesc: 'Edits code, runs tests, watches the terminal',
  agentQa: 'Quality and safety',
  agentQaDesc: 'Acceptance, permissions, and risk checks',
  discoverPlugins: 'Plugin market',
  discoverSkills: 'Skills',
  discoverWorkflows: 'Workflows',
  statusQueued: 'Queued',
  statusRunning: 'Running',
  statusWaiting: 'Needs confirmation',
  // —— Copy added with the real-model wiring: settings, send states, history ——
  modelPickerTitle: 'Choose a model',
  modelNotConfigured: 'No model configured',
  modelPickerEmpty: 'No models available yet. Open Me → Model settings and fill in an endpoint and a model name.',
  settingsTitle: 'Model settings',
  settingsProvider: 'Provider',
  settingsBaseUrl: 'Endpoint',
  settingsBaseUrlHint: 'An OpenAI-compatible base URL, usually ending in /v1.',
  settingsApiKey: 'API key',
  settingsApiKeyPlaceholder: 'Paste your key',
  settingsShow: 'Show',
  settingsHide: 'Hide',
  settingsModel: 'Model',
  settingsModelHint: 'Use the model name from your provider docs, for example gpt-4o-mini.',
  settingsSave: 'Save',
  settingsSaved: 'Saved on this device',
  settingsTest: 'Test connection',
  settingsTesting: 'Testing…',
  settingsTestOk: 'Connected. The configuration works.',
  settingsPrivacy: 'The key stays on this device and is never uploaded to any server. But localStorage is not encrypted storage: anyone who can reach this device can read it.',
  settingsBack: 'Back',
  settingsStorageFailed: 'Writing to local storage failed (private mode, or the quota is full). This change was not saved.',
  sessionsEmpty: 'No conversation on this phone yet. Send one and it appears here.',
  sessionsHint: 'Local conversations continue on the model you configured; a command sent to the PC is a separate record that stores only the delivery state, because execution and results live on the PC.',
  history: 'History',
  stop: 'Stop',
  streaming: 'Replying…',
  thinking: 'Thinking',
  idle: 'Ready',
  aborted: 'Stopped',
  testNeedEndpoint: 'Fill in the endpoint before testing.',
  testNeedKey: 'Fill in the API key before testing.',
  testTimeout: 'The test timed out. The provider did not respond within 15 seconds.',
  // —— Copy added with the two-capability merge: mode bar, mode picker, split history, empty states ——
  modePickerTitle: 'Who answers this message',
  modeLocal: 'This phone answers',
  modeRemote: 'Send to the PC',
  modeBarLocalOnly: 'The PC is unreachable, so this phone answers',
  modeBarLocalReady: 'This phone answers; the PC is also available',
  modeBarRemote: 'This message goes to the PC',
  modeUsePc: 'Use the PC',
  modeUseLocal: 'Use the phone',
  modePcFellBack: 'The PC is unreachable right now, so the phone answers this one',
  modeRemoteHint: 'Pick "Send to the PC" below.',
  settingsLocalTitle: 'This phone owns its model',
  settingsLocalHint: 'Requests go from this device straight to your provider, never through a Qianshou server, and the PC does not have to be on.',
  settingsPcOptional: 'The PC connection is optional: while it is unreachable the phone keeps talking and loses no records.',
  remoteRecordHint: 'These are commands sent to the PC. They show the delivery state only; execution and results live on the PC.',
  sessionsLocalTitle: 'Conversations on this phone',
  sessionsPcTitle: 'Commands sent to the PC',
  sessionsRecordsEmpty: 'No commands sent to the PC yet. Switch the mode to "Send to the PC" and the records appear here.',
  meModeLabel: 'How this phone works',
  liveJobsNone: 'Live task data is not connected yet, so this area is empty.',
  liveJobsEmpty: 'Live task data is not connected yet',
  // —— Home tiles: the copy used to hang off Chinese strings in data.ts (`t[tile.title]`),
  //    which the locale table has no key for, so the UI rendered undefined. Now keyed by tile.id. ——
  tileCreateTitle: 'Create an agent',
  tileCreateDesc: 'A team of AIs working for you',
  tileRunTitle: 'Task runs',
  tileRunDesc: 'Dispatch · Run · Monitor',
  tileFlowTitle: 'Workflows',
  tileFlowDesc: 'Automate your business',
  tileDataTitle: 'Data analysis',
  tileDataDesc: 'Find value in your data',
  // —— Web search: say up front which route this message takes once the chip is on ——
  searchBarRemote: 'The PC will answer this one with a web search',
  searchBarPhone: 'The PC is offline; this phone will search the web with your own key',
  searchBarOffline: 'The PC is offline, so a web search is unavailable; the model on this phone answers this one and may lack the latest information',
  searchBarUnsupported: 'This provider does not support web search here; the model on this phone answers this one and may lack the latest information',
  // The subscription channel is chat-only: this says "no", not "not yet".
  searchBarSubscription: 'The subscription channel has no web search; this one is answered directly without the latest information',
  // —— Subscription channel: which route is in effect, and how much credit is left ——
  routeTitle: 'Chat channel',
  routeNowSubscription: 'Subscription channel is in use (the account subscription pays; no API key needed)',
  routeNowByok: 'Your own key is in use (requests go straight from this device to your provider)',
  creditLabel: 'Left',
  creditUnit: 'SP',
  creditReading: 'Reading credit…',
  creditUnknown: 'Credit unknown',
  // —— Search phases: "searching" and "reading" are separate states, not one vague "replying" ——
  searchSearching: 'Searching the web…',
  searchReading: 'Reading results…',
  searchSources: 'This answer cited {n} web sources',

}

export type Locale = 'zh' | 'en'

export function copyOf(locale: Locale): Copy {
  return locale === 'en' ? en : zh
}
