// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import type { Context } from '@deepseek-ai/cordis'
import type { AccountSnapshot } from '@deepseek-ai/dsh-api-remotes/client'
import { bindSnapshotSelector } from '@deepseek-ai/dsh-client-test-runtime'
import { AccountController } from '../src/client/controller.ts'
import { AccountPanel, AccountEntry, type AccountPanelProps } from '../src/client/AccountPanel.tsx'
import { zh } from '../src/client/locales.ts'
import { apply } from '../src/client/index.ts'

afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const signedOut: AccountSnapshot = { phase: 'signed-out', account: null, failure: null, restorable: false, verifiedAt: null, models: [], cloudSelected: false }
const signedIn: AccountSnapshot = { ...signedOut, phase: 'authenticated', account: { id: 'user1', username: 'fixture-user' }, verifiedAt: 1, restorable: true }
function fixture(state = signedOut) {
  const ok = (value: AccountSnapshot) => ({ ok: true as const, value })
  const commerce = { tierLabel: 'Max 版', remainingSp: 12, windowLimitSp: 600, usedInWindowSp: 600, balanceYuan: '1.00',
    plans: [{ id: 'max', label: 'Max 版', monthlyYuan: 299, monthlySp: 2990 }],
    quote: null, notice: null }
  const remote = { state: vi.fn(async () => ok(state)), login: vi.fn(async () => ok(signedIn)),
    sendPhoneCode: vi.fn(async () => ok(state)), loginWithPhone: vi.fn(async () => ok(signedIn)), registerWithPhone: vi.fn(async () => ok(signedIn)),
    completeTotp: vi.fn(async () => ok(signedIn)), cancel: vi.fn(async () => ok(signedOut)),
    reconnect: vi.fn(async () => ok({ ...signedIn, models: ['fixture-model'] })), logout: vi.fn(async () => ok(signedOut)),
    useCloud: vi.fn(async () => ok({ ...signedIn, cloudSelected: true })),
    billing: vi.fn(async () => ({ ok: true as const, value: commerce })),
    quotePlan: vi.fn(async () => ({ ok: true as const, value: { ...commerce, quote: { label: 'Max 版', amountYuan: '299.00', monthlySp: 2990, canPay: false } } })),
    buyPlan: vi.fn(async () => ({ ok: true as const, value: { ...commerce, notice: 'paid' as const } })),
    startRecharge: vi.fn(async () => ({ ok: true as const, value: { action: 'https://openapi.alipay.com/gateway.do?charset=utf-8', fields: [] } })) }
  const emit = vi.fn()
  const controller = new AccountController({ emit, remote: { qianshouAccount: remote } } as unknown as Context)
  const props = { controller, useAccount: bindSnapshotSelector(controller.store), t: (key: keyof typeof zh, params?: Record<string, string>) => Object.entries(params ?? {}).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), zh[key]) } as AccountPanelProps
  return { controller, remote, props, emit }
}

describe('account actions and presentation', () => {
  it.each([undefined, 'default'])('registers no account UI outside Qianshou builds: %s', (profile) => {
    vi.stubEnv('DSH_CLIENT_BUILD_PROFILE', profile)
    const effect = vi.fn()
    const register = vi.fn()
    const inject = vi.fn()
    try {
      apply({ effect, locale: { register }, slots: { inject } } as unknown as Context)
      expect(effect).not.toHaveBeenCalled()
      expect(register).not.toHaveBeenCalled()
      expect(inject).not.toHaveBeenCalled()
    } finally {
      vi.unstubAllEnvs()
    }
  })
  it('loads real Host status and restores a persisted login only once', async () => {
    const { controller, remote } = fixture({ ...signedOut, restorable: true })
    await controller.load(); await controller.load()
    expect(remote.reconnect).toHaveBeenCalledTimes(1)
    expect(remote.useCloud).not.toHaveBeenCalled()
  })
  it('never lets a late login result resurrect status after cancel', async () => {
    const { controller, remote } = fixture()
    let finish!: (value: Awaited<ReturnType<typeof remote.login>>) => void
    remote.login.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve }))
    const pending = controller.login('fixture-user', 'fixture-password')
    await controller.cancel(); finish({ ok: true, value: signedIn }); await pending
    expect(controller.store.getSnapshot()).toMatchObject({ snapshot: signedOut, busy: false, failed: false })
  })
  it('invalidates account-bound views only after a real owner transition', async () => {
    const { controller, emit } = fixture()
    await controller.load()
    expect(emit).not.toHaveBeenCalled()
    await controller.login('fixture-user', 'fixture-password')
    expect(emit).toHaveBeenCalledWith('qianshou-account/identity-changed', 'user1')
    await controller.logout()
    expect(emit).toHaveBeenLastCalledWith('qianshou-account/identity-changed', null)
  })
  it('sends credentials directly, clears the password input and preserves the selected route', async () => {
    const { remote, props, controller } = fixture()
    render(<AccountPanel {...props} />)
    expect(screen.getByRole('heading', { name: '欢迎使用千手' })).toBeTruthy()
    expect(document.querySelector('[data-qianshou-account] img[src="/brand/qianshou-mark.png"]')).toBeTruthy()
    await waitFor(() => { expect(screen.getByRole('status').textContent).toBe('未登录') })
    fireEvent.change(screen.getByLabelText('账号或邮箱'), { target: { value: 'fixture-user' } })
    fireEvent.change(screen.getByLabelText('密码'), { target: { value: 'fixture-password' } })
    fireEvent.submit(screen.getByRole('button', { name: '登录' }).closest('form')!)
    await waitFor(() => { expect(screen.getByText('fixture-user')).toBeTruthy() })
    expect(remote.login).toHaveBeenCalledWith('fixture-user', 'fixture-password')
    expect(remote.useCloud).not.toHaveBeenCalled()
    expect(JSON.stringify(controller.store.getSnapshot())).not.toContain('fixture-password')
    fireEvent.click(screen.getByRole('button', { name: '使用千手模型' }))
    await waitFor(() => { expect(remote.useCloud).toHaveBeenCalledTimes(1) })
    expect(screen.getByText(zh.selected)).toBeTruthy()
    await waitFor(() => { expect(remote.billing).toHaveBeenCalled() })
    expect(screen.getByText('已用 600 / 600 SP')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: /管理套餐/ }))
    fireEvent.click(screen.getByRole('button', { name: /Max 版/ }))
    await waitFor(() => { expect(remote.quotePlan).toHaveBeenCalledWith('max') })
    expect(screen.getByText('支付 ¥299.00')).toBeTruthy()
    expect(screen.getByRole('button', { name: '确认开通' }).hasAttribute('disabled')).toBe(true)
  })
  it('offers Host-backed account login, phone login and phone registration', async () => {
    const { remote, props } = fixture()
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('tab', { name: '账号登录' }).getAttribute('aria-selected')).toBe('true') })
    expect(screen.queryByRole('tab', { name: '扫码' })).toBeNull()
    expect(remote.login).not.toHaveBeenCalled()
    expect(remote.loginWithPhone).not.toHaveBeenCalled()
    const accountTab = screen.getByRole('tab', { name: '账号登录' })
    accountTab.focus()
    fireEvent.keyDown(accountTab, { key: 'ArrowRight' })
    expect(screen.getByRole('tab', { name: '手机登录' }).getAttribute('aria-selected')).toBe('true')
    expect(document.activeElement).toBe(screen.getByRole('tab', { name: '手机登录' }))
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '13800138000' } })
    fireEvent.click(screen.getByRole('button', { name: '发送登录验证码' }))
    await waitFor(() => { expect(remote.sendPhoneCode).toHaveBeenCalledWith('13800138000', 'login') })
    fireEvent.change(screen.getByRole('textbox', { name: '短信验证码' }), { target: { value: '123456' } })
    fireEvent.submit(screen.getByRole('textbox', { name: '短信验证码' }).closest('form')!)
    await waitFor(() => { expect(remote.loginWithPhone).toHaveBeenCalledWith('13800138000', '123456') })
  })
  it('sends a registration code and creates a real account only after submit', async () => {
    const { remote, props } = fixture()
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('status').textContent).toBe('未登录') })
    fireEvent.click(screen.getByRole('tab', { name: '手机注册' }))
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '13800138000' } })
    fireEvent.click(screen.getByRole('button', { name: '发送注册验证码' }))
    await waitFor(() => { expect(remote.sendPhoneCode).toHaveBeenCalledWith('13800138000', 'register') })
    expect(remote.registerWithPhone).not.toHaveBeenCalled()
    fireEvent.change(screen.getByRole('textbox', { name: '短信验证码' }), { target: { value: '123456' } })
    fireEvent.click(screen.getByRole('button', { name: '注册并登录' }))
    await waitFor(() => { expect(remote.registerWithPhone).toHaveBeenCalledWith('13800138000', '123456') })
  })
  it('keeps method, purpose, and submit state unambiguous while a code is entered', async () => {
    const { remote, props } = fixture()
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('tab', { name: '手机登录' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('tab', { name: '手机登录' }))
    expect(screen.getByRole('tab', { name: '手机登录' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('tab', { name: '手机注册' }).getAttribute('aria-selected')).toBe('false')
    expect(screen.getByRole('button', { name: '发送登录验证码' }).hasAttribute('disabled')).toBe(true)
    expect(screen.getByRole('button', { name: '登录' }).hasAttribute('disabled')).toBe(true)

    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '12345' } })
    expect(screen.getByRole('button', { name: '发送登录验证码' }).hasAttribute('disabled')).toBe(true)
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '12800138000' } })
    expect(screen.getByRole('button', { name: '发送登录验证码' }).hasAttribute('disabled')).toBe(true)
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '86 (138)0013-8000' } })
    expect(screen.getByRole('button', { name: '发送登录验证码' }).hasAttribute('disabled')).toBe(false)
    const codeInput = screen.getByRole('textbox', { name: '短信验证码' })
    const hintId = codeInput.getAttribute('aria-describedby')
    expect(hintId).toBeTruthy()
    expect(document.getElementById(hintId!)?.textContent).toContain('六位数字验证码')
    fireEvent.change(codeInput, { target: { value: '12345' } })
    expect(screen.getByRole('button', { name: '登录' }).hasAttribute('disabled')).toBe(true)
    fireEvent.change(codeInput, { target: { value: '１２３４５６' } })
    expect(screen.getByRole('button', { name: '登录' }).hasAttribute('disabled')).toBe(true)
    fireEvent.change(codeInput, { target: { value: '123456' } })
    expect(screen.getByRole('button', { name: '登录' }).hasAttribute('disabled')).toBe(false)
    expect(remote.loginWithPhone).not.toHaveBeenCalled()

    fireEvent.click(screen.getByRole('tab', { name: '手机注册' }))
    expect(screen.getByRole('tab', { name: '手机注册' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('tab', { name: '手机登录' }).getAttribute('aria-selected')).toBe('false')
    expect(screen.getByRole('button', { name: '发送注册验证码' })).toBeTruthy()
    expect(screen.getByRole('button', { name: '注册并登录' }).hasAttribute('disabled')).toBe(true)
    expect((screen.getByRole('textbox', { name: '短信验证码' }) as HTMLInputElement).value).toBe('')
  })
  it('keeps a rejected registration code for correction and hides the earlier send notice', async () => {
    const { remote, props } = fixture()
    remote.registerWithPhone.mockResolvedValueOnce({ ok: true, value: { ...signedOut, failure: 'invalid-input' } })
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('tab', { name: '手机注册' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('tab', { name: '手机注册' }))
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '13800138000' } })
    fireEvent.click(screen.getByRole('button', { name: '发送注册验证码' }))
    await waitFor(() => { expect(screen.getByText(zh.registerCodeSent)).toBeTruthy() })
    fireEvent.change(screen.getByRole('textbox', { name: '短信验证码' }), { target: { value: '123456' } })
    fireEvent.click(screen.getByRole('button', { name: '注册并登录' }))
    await waitFor(() => { expect(screen.getByRole('alert').textContent).toBe(zh['invalid-input']) })
    expect((screen.getByRole('textbox', { name: '短信验证码' }) as HTMLInputElement).value).toBe('123456')
    expect(screen.queryByText(zh.registerCodeSent)).toBeNull()
    expect(zh['invalid-input']).not.toContain('六位')
    expect(remote.registerWithPhone).toHaveBeenCalledWith('13800138000', '123456')
    fireEvent.click(screen.getByRole('button', { name: '发送注册验证码' }))
    await waitFor(() => { expect(screen.getByText(zh.registerCodeSent)).toBeTruthy() })
    expect(screen.queryByRole('alert')).toBeNull()
  })
  it('ignores an old registration SMS response after switching to phone sign-in', async () => {
    const { remote, props } = fixture()
    let finish!: (result: Awaited<ReturnType<typeof remote.sendPhoneCode>>) => void
    remote.sendPhoneCode.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('tab', { name: '手机注册' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('tab', { name: '手机注册' }))
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '13800138000' } })
    fireEvent.click(screen.getByRole('button', { name: '发送注册验证码' }))
    expect(remote.sendPhoneCode).toHaveBeenCalledWith('13800138000', 'register')
    fireEvent.click(screen.getByRole('tab', { name: '手机登录' }))
    await act(async () => { finish({ ok: true, value: signedOut }) })
    expect(screen.getByRole('tab', { name: '手机登录' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('button', { name: '登录' })).toBeTruthy()
    expect(screen.queryByText(zh.registerCodeSent)).toBeNull()
    expect(screen.queryByText(zh.loginCodeSent)).toBeNull()
    expect((screen.getByRole('textbox', { name: '短信验证码' }) as HTMLInputElement).value).toBe('')
  })
  it('keeps the phone registration form and number visible throughout a successful SMS request', async () => {
    const { remote, props } = fixture()
    let finish!: (result: Awaited<ReturnType<typeof remote.sendPhoneCode>>) => void
    remote.sendPhoneCode.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('tab', { name: '手机注册' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('tab', { name: '手机注册' }))
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '13800138000' } })
    fireEvent.click(screen.getByRole('button', { name: '发送注册验证码' }))

    expect(screen.getByRole('tab', { name: '手机注册' }).getAttribute('aria-selected')).toBe('true')
    expect((screen.getByRole('textbox', { name: '手机号' }) as HTMLInputElement).value).toBe('13800138000')
    expect(screen.getByRole('button', { name: '发送注册验证码' }).hasAttribute('disabled')).toBe(true)
    await act(async () => { finish({ ok: true, value: signedOut }) })

    await waitFor(() => { expect(screen.getByText(zh.registerCodeSent)).toBeTruthy() })
    expect(screen.getByRole('tab', { name: '手机注册' }).getAttribute('aria-selected')).toBe('true')
    expect((screen.getByRole('textbox', { name: '手机号' }) as HTMLInputElement).value).toBe('13800138000')
    expect(remote.registerWithPhone).not.toHaveBeenCalled()
  })
  it('does not claim a text code was sent when the Host request fails', async () => {
    const { remote, props } = fixture()
    remote.sendPhoneCode.mockRejectedValueOnce(new Error('private-sms-error'))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('tab', { name: '手机登录' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('tab', { name: '手机登录' }))
    fireEvent.change(screen.getByRole('textbox', { name: '手机号' }), { target: { value: '13800138000' } })
    fireEvent.click(screen.getByRole('button', { name: '发送登录验证码' }))
    await waitFor(() => { expect(screen.getByRole('alert').textContent).toBe(zh['connection-failed']) })
    expect(screen.queryByText(zh.loginCodeSent)).toBeNull()
    expect(screen.queryByText('private-sms-error')).toBeNull()
  })
  it('renders the Host 2FA step and sends only the entered code and trust choice', async () => {
    const { remote, props } = fixture({ ...signedOut, phase: 'two-factor-required' })
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByLabelText('六位验证码')).toBeTruthy() })
    expect(screen.getByRole('heading', { name: '完成安全验证' })).toBeTruthy()
    expect(screen.queryByLabelText('密码')).toBeNull()
    fireEvent.change(screen.getByLabelText('六位验证码'), { target: { value: '123456' } })
    fireEvent.click(screen.getByLabelText('信任此设备'))
    fireEvent.click(screen.getByRole('button', { name: '完成验证' }))
    await waitFor(() => { expect(remote.completeTotp).toHaveBeenCalledWith('123456', true) })
  })
  it('shows a safe connection failure without claiming a verified account', async () => {
    const { remote, props } = fixture()
    remote.state.mockRejectedValueOnce(new Error('private-host-details'))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('alert').textContent).toBe(zh['connection-failed']) })
    expect(screen.queryByText('private-host-details')).toBeNull()
    expect(screen.queryByRole('button', { name: '使用千手模型' })).toBeNull()
  })
  it('opens the personal center in one click and leaves secondary actions in a short menu', async () => {
    const { props, remote } = fixture(signedIn)
    const open = vi.fn()
    window.addEventListener('qianshou:open-settings', open)
    try {
      render(<AccountEntry {...({ ...props, wide: true } as unknown as Parameters<typeof AccountEntry>[0])} />)
      const trigger = screen.getByRole('button', { name: '打开个人中心' })
      await waitFor(() => { expect(trigger.getAttribute('title')).toBe('fixture-user') })
      fireEvent.click(trigger)
      expect(open).toHaveBeenCalledTimes(1)
      expect((open.mock.calls[0]?.[0] as CustomEvent<{ sectionId: string }>).detail.sectionId).toBe('qianshou-account')
      expect(screen.queryByRole('menu')).toBeNull()
      fireEvent.click(screen.getByRole('button', { name: '千手账号菜单' }))
      const menu = screen.getByRole('menu')
      expect(menu.querySelector('[data-qianshou-account-menu]')).toBeTruthy()
      expect(menu.textContent).toContain('fixture-user')
      expect(menu.textContent).toContain('账号已验证')
      expect(screen.getByRole('menuitem', { name: '账号、用量与套餐' })).toBeTruthy()
      expect(screen.getByRole('menuitem', { name: '设置' })).toBeTruthy()
      expect(screen.getByRole('menuitem', { name: '千手云' })).toBeTruthy()
      expect(screen.getByRole('menuitem', { name: '帮助与支持' })).toBeTruthy()
      expect(screen.queryByRole('menuitem', { name: '检查更新' })).toBeNull()
      expect(screen.getByRole('menuitem', { name: '退出登录' })).toBeTruthy()
      expect(screen.queryByLabelText('充值金额（元）')).toBeNull()
      expect(remote.billing).not.toHaveBeenCalled()
      fireEvent.click(screen.getByRole('menuitem', { name: '设置' }))
      expect(open).toHaveBeenCalledTimes(2)
      expect((open.mock.calls[1]?.[0] as CustomEvent<{ sectionId: string }>).detail.sectionId).toBe('general')
      expect(screen.queryByRole('menuitem', { name: '设置' })).toBeNull()
    } finally {
      window.removeEventListener('qianshou:open-settings', open)
    }
  })
  it('shows account management in personal center and cancelling does not sign out', async () => {
    const { remote, props } = fixture(signedIn)
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('region', { name: '账号管理' })).toBeTruthy() })
    expect(screen.getByRole('button', { name: '切换账号' })).toBeTruthy()
    expect(screen.queryByRole('button', { name: /注销/ })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: '退出登录' }))
    expect(screen.getByRole('dialog', { name: '退出当前登录？' })).toBeTruthy()
    expect(screen.getByText(zh.logoutConfirmHint)).toBeTruthy()
    expect(remote.logout).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: '暂不退出' }))
    expect(screen.queryByRole('dialog')).toBeNull()
    expect(remote.logout).not.toHaveBeenCalled()
    expect(screen.getByText('fixture-user')).toBeTruthy()
  })
  it.each(['退出登录', '切换账号'])('requires confirmation before %s and returns to the genuine sign-in form', async (action) => {
    const { remote, props, emit } = fixture(signedIn)
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('button', { name: action })).toBeTruthy() })
    fireEvent.click(screen.getByRole('button', { name: action }))
    expect(remote.logout).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: action === '切换账号' ? '退出并切换账号' : '确认退出登录' }))
    await waitFor(() => { expect(screen.getByRole('button', { name: '登录' })).toBeTruthy() })
    expect(remote.logout).toHaveBeenCalledTimes(1)
    expect(emit).toHaveBeenLastCalledWith('qianshou-account/identity-changed', null)
    expect(screen.queryByRole('region', { name: '账号管理' })).toBeNull()
    expect(screen.getByLabelText('账号或邮箱')).toBeTruthy()
    expect(remote.startRecharge).not.toHaveBeenCalled()
    expect(remote.buyPlan).not.toHaveBeenCalled()
  })
  it('does not permit repeated confirmation while the real logout operation is pending', async () => {
    const { remote, props } = fixture(signedIn)
    let finish!: (value: Awaited<ReturnType<typeof remote.logout>>) => void
    remote.logout.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('button', { name: '退出登录' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('button', { name: '退出登录' }))
    fireEvent.click(screen.getByRole('button', { name: '确认退出登录' }))
    const pending = screen.getByRole('button', { name: '正在处理…' })
    expect(pending.hasAttribute('disabled')).toBe(true)
    fireEvent.click(pending)
    expect(remote.logout).toHaveBeenCalledTimes(1)
    await act(async () => { finish({ ok: true, value: signedOut }) })
    expect(screen.queryByRole('dialog')).toBeNull()
  })
  it('keeps authentication visible and reports a failed logout instead of claiming success', async () => {
    const { remote, props } = fixture(signedIn)
    remote.logout.mockRejectedValueOnce(new Error('fixture unavailable'))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('button', { name: '退出登录' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('button', { name: '退出登录' }))
    fireEvent.click(screen.getByRole('button', { name: '确认退出登录' }))
    await waitFor(() => { expect(screen.getAllByRole('alert').some(alert => alert.textContent === zh['connection-failed'])).toBe(true) })
    expect(screen.getByRole('dialog', { name: '退出当前登录？' })).toBeTruthy()
    expect(screen.getByText('fixture-user')).toBeTruthy()
    expect(screen.queryByRole('button', { name: '登录' })).toBeNull()
    expect(remote.logout).toHaveBeenCalledTimes(1)
  })
  it('invalidates an old confirmation after a real account change', async () => {
    const { controller, remote, props } = fixture(signedIn)
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByRole('button', { name: '退出登录' })).toBeTruthy() })
    fireEvent.click(screen.getByRole('button', { name: '退出登录' }))
    const staleConfirm = screen.getByRole('button', { name: '确认退出登录' })
    remote.login.mockResolvedValueOnce({ ok: true, value: { ...signedIn, account: { id: 'user2', username: 'next-owner' } } })
    await act(async () => { await controller.login('next-owner', 'fixture-password') })
    expect(screen.queryByRole('dialog')).toBeNull()
    expect(screen.getByText('next-owner')).toBeTruthy()
    fireEvent.click(staleConfirm)
    expect(remote.logout).not.toHaveBeenCalled()
  })
  it('also confirms the sidebar sign-out action rather than logging out from a menu click', async () => {
    const { remote, props } = fixture(signedIn)
    render(<AccountEntry {...({ ...props, wide: true } as unknown as Parameters<typeof AccountEntry>[0])} />)
    await waitFor(() => { expect(screen.getByRole('button', { name: '打开个人中心' }).getAttribute('title')).toBe('fixture-user') })
    fireEvent.click(screen.getByRole('button', { name: '千手账号菜单' }))
    fireEvent.click(screen.getByRole('menuitem', { name: '退出登录' }))
    expect(screen.queryByRole('menu')).toBeNull()
    expect(screen.getByRole('dialog', { name: '退出当前登录？' })).toBeTruthy()
    expect(remote.logout).not.toHaveBeenCalled()
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.queryByRole('dialog')).toBeNull()
    expect(remote.logout).not.toHaveBeenCalled()
  })
  it('shows the installed build version in About instead of requiring a footer badge', async () => {
    vi.stubEnv('DSH_CLIENT_VERSION', '0.1.6-alpha.2')
    const original = Object.getOwnPropertyDescriptor(HTMLDialogElement.prototype, 'showModal')
    Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value() {} })
    try {
      const { props } = fixture(signedIn)
      render(<AccountEntry {...({ ...props, wide: true } as unknown as Parameters<typeof AccountEntry>[0])} />)
      fireEvent.click(screen.getByRole('button', { name: '千手账号菜单' }))
      fireEvent.click(screen.getByRole('menuitem', { name: '关于千手' }))
      expect(screen.getByText('版本 0.1.6-alpha.2')).toBeTruthy()
      expect(document.querySelector('dialog img[src="/brand/qianshou-mark.png"]')).toBeTruthy()
    } finally {
      if (original === undefined) delete (HTMLDialogElement.prototype as Partial<HTMLDialogElement>).showModal
      else Object.defineProperty(HTMLDialogElement.prototype, 'showModal', original)
      vi.unstubAllEnvs()
    }
  })
  it('returns keyboard focus to the avatar chip when Escape closes the menu', async () => {
    const { props } = fixture(signedIn)
    render(<AccountEntry {...({ ...props, wide: true } as unknown as Parameters<typeof AccountEntry>[0])} />)
    const trigger = screen.getByRole('button', { name: '千手账号菜单' })
    trigger.focus()
    fireEvent.click(trigger)
    await waitFor(() => { expect(document.activeElement).toBe(screen.getByRole('menuitem', { name: '账号、用量与套餐' })) })
    fireEvent.keyDown(document, { key: 'Escape' })
    await waitFor(() => { expect(screen.queryByRole('menuitem', { name: '账号、用量与套餐' })).toBeNull() })
    expect(document.activeElement).toBe(trigger)
  })
  it('offers native update only with a desktop updater and sends help to the published support page', () => {
    vi.stubGlobal('dshDesktop', { protocolVersion: 1, updates: {} })
    const openExternal = vi.spyOn(window, 'open').mockImplementation(() => null)
    const onUpdate = vi.fn()
    window.addEventListener('qianshou:open-update', onUpdate)
    try {
      const { props } = fixture(signedIn)
      render(<AccountEntry {...({ ...props, wide: true } as unknown as Parameters<typeof AccountEntry>[0])} />)
      fireEvent.click(screen.getByRole('button', { name: '千手账号菜单' }))
      fireEvent.click(screen.getByRole('menuitem', { name: '检查更新' }))
      expect(onUpdate).toHaveBeenCalledTimes(1)
      fireEvent.click(screen.getByRole('button', { name: '千手账号菜单' }))
      fireEvent.click(screen.getByRole('menuitem', { name: '帮助与支持' }))
      expect(openExternal).toHaveBeenCalledWith('https://qianshousuanli.com/#/downloads', '_blank', 'noopener,noreferrer')
    } finally {
      window.removeEventListener('qianshou:open-update', onUpdate)
      openExternal.mockRestore()
    }
  })
  it('routes a signed-out user to the account page and keeps their account state untouched', async () => {
    const { props, remote } = fixture()
    const open = vi.fn()
    window.addEventListener('qianshou:open-settings', open)
    try {
      render(<AccountEntry {...({ ...props, wide: true } as unknown as Parameters<typeof AccountEntry>[0])} />)
      expect(screen.getByRole('button', { name: '打开个人中心' }).querySelector('img[src="/brand/qianshou-mark.png"]')).toBeTruthy()
      fireEvent.click(screen.getByRole('button', { name: '打开个人中心' }))
      expect((open.mock.calls[0]?.[0] as CustomEvent<{ sectionId: string }>).detail.sectionId).toBe('qianshou-account')
      expect(screen.queryByRole('menu')).toBeNull()
      expect(remote.login).not.toHaveBeenCalled()
    } finally {
      window.removeEventListener('qianshou:open-settings', open)
    }
  })
  it('keeps the full username in a tooltip and an avatar in a narrow sidebar', async () => {
    const username = '千手账号显示名称'.repeat(8)
    const { props } = fixture({ ...signedIn, account: { id: 'user1', username } })
    const renderEntry = (wide: boolean) => <AccountEntry {...({ ...props, wide } as unknown as Parameters<typeof AccountEntry>[0])} />
    const { rerender } = render(renderEntry(false))
    const button = screen.getByRole('button', { name: '打开个人中心' })
    await waitFor(() => { expect(button.getAttribute('title')).toBe(username) })
    expect(button.textContent).toBe('千')
    rerender(renderEntry(true))
    expect(button.textContent).toContain(username)
    expect(button.getAttribute('title')).toBe(username)
    expect(button.querySelector('svg')).toBeNull()
  })
  it('separates unavailable billing from authentication and never invents a balance', async () => {
    const { props, remote } = fixture(signedIn)
    remote.billing.mockRejectedValueOnce(new Error('billing-private-failure'))
    render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByText(zh.commerceUnavailable)).toBeTruthy() })
    expect(screen.queryByText(zh['connection-failed'])).toBeNull()
    expect(screen.queryByText('¥1.00')).toBeNull()
    expect(screen.getAllByText(zh.unread).length).toBeGreaterThan(0)
    const previousCalls = remote.billing.mock.calls.length
    fireEvent.click(screen.getByRole('button', { name: '重试' }))
    await waitFor(() => { expect(remote.billing.mock.calls.length).toBeGreaterThan(previousCalls) })
  })
  it('keeps the four account facts exact and opens plan or recharge views without initiating payment', async () => {
    const { props, remote } = fixture(signedIn)
    render(<AccountPanel {...props} />)
    await screen.findByText('¥1.00')
    const plan = screen.getByRole('region', { name: zh.planTitle })
    expect(plan.textContent).toContain('Max 版')
    expect(plan.textContent).toContain('剩余 12 SP')
    expect(screen.getByRole('region', { name: zh.walletTitle }).textContent).toContain('¥1.00')
    const meter = screen.getByRole('progressbar', { name: '已用 600 / 600 SP' })
    expect(meter.getAttribute('aria-valuenow')).toBe('600')
    expect(meter.getAttribute('aria-valuemax')).toBe('600')
    expect(screen.getByRole('region', { name: zh.incomeTitle }).textContent).not.toContain('¥1.00')
    fireEvent.click(screen.getByRole('button', { name: new RegExp(zh.managePlan) }))
    expect(screen.getByRole('region', { name: zh.subscribe })).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: zh.backToAccount }))
    fireEvent.click(screen.getByRole('button', { name: new RegExp(`^${zh.rechargeTitle}`) }))
    expect(screen.getByRole('region', { name: zh.rechargeTitle })).toBeTruthy()
    expect(remote.quotePlan).not.toHaveBeenCalled()
    expect(remote.buyPlan).not.toHaveBeenCalled()
    expect(remote.startRecharge).not.toHaveBeenCalled()
  })
  it('keeps income separate from wallet balance and opens the real intake page', async () => {
    const { props } = fixture(signedIn)
    const openIntake = vi.fn()
    window.addEventListener('qianshou:open-intake', openIntake)
    try {
      render(<AccountPanel {...props} />)
      await waitFor(() => { expect(screen.getByText('¥1.00')).toBeTruthy() })
      const income = screen.getByRole('region', { name: '接单收入' })
      expect(income.textContent).toContain('在接单页查看')
      expect(income.textContent).not.toContain('¥1.00')
      fireEvent.click(screen.getByRole('button', { name: /查看接单记录/ }))
      expect(openIntake).toHaveBeenCalledOnce()
    } finally {
      window.removeEventListener('qianshou:open-intake', openIntake)
    }
  })
  it('keeps account failures and data limitations visible without exposing private errors', async () => {
    const { props } = fixture({ ...signedIn, phase: 'unavailable', failure: 'rate-limited', models: ['fixture-model'] })
    const { container } = render(<AccountPanel {...props} />)
    await waitFor(() => { expect(screen.getByText(zh['rate-limited'])).toBeTruthy() })
    expect(container.textContent).not.toContain('billing-private-failure')
    expect(screen.getByText('Max 版')).toBeTruthy()
  })
})
