/** Product text belongs to the preview locale, not the renderer. */
export const copy = {
  viewFailure: { navigation: '会话列表暂未刷新，聊天可以继续。', transcript: '回复排版暂未刷新，已保留上一版内容。', account: '账号信息暂未刷新，聊天可以继续。' },
  brand: '千手 AI', menu: '打开侧边栏', close: '关闭', newChat: '新对话', login: '登录', account: '我的账号',
  hello: '想做什么，和千手聊聊', subtitle: '从一个想法开始，让事情一步步完成。',
  image: '创作一张图片', video: '制作一段视频', sheet: '整理一份表格',
  imagePrompt: '给我出一张图', videoPrompt: '帮我做一个视频', sheetPrompt: '帮我做一份表格',
  inputHint: '想法、问题，或者要完成的工作…', send: '发送消息', intro: '手机随时交流，电脑接续工作',
  preview: '千手 AI 网页版', disconnected: '服务待连接', loginHint: '登录后，查看同账号下的电脑和会话。',
  username: '用户名或邮箱', password: '密码', totp: '动态验证码', totpHint: '请输入验证器中的 6 位验证码',
  submitting: '正在验证…', verify: '验证并登录', sessionOnly: '本次登录只在当前页面有效，刷新页面后需重新登录。',
  loginFailed: '登录未完成，请检查账号、密码或连接设置。', accountUnknown: '账号身份未确认，请重新登录。',
  logout: '退出登录', logoutFailed: '本页已退出；服务器撤销未确认。', settings: '连接设置', accountService: '账号服务',
  cloudService: '移动端智能体', pcService: '远程电脑', configured: '已配置连接，需登录后核验', connected: '已配置', missing: '尚未接入',
  settingsHelp: '查看账号、智能体和远程电脑的连接状态。电脑会话需要同账号登录并授权。',
  back: '返回', loginFirst: '请先登录，再开始会话', agentMissing: '移动端智能体服务尚未连接',
  pcMissing: '电脑会话连接尚未接入', draftTitle: '需求草稿', draftHint: '仅整理输入，发送后由千手智能体理解和确认。',
  draftFree: '可以自由发挥，创作细节待智能体确认', draftImageRoute: '广州号池出图。点「确认出图」后才会发一次请求，不会自动重试。', draftComputeRoute: '将由智能体匹配分布式能力，当前只准备需求。', draftAgentRoute: '将由智能体继续判断，暂未开放独立执行路由。', draftSpecified: '已保留输入中的具体要求', draftClarify: '还需要确认主体或参考内容', imageBusy: '这一张还在画。', imageDone: '图片已生成。',
  imageWaitTitle: '正在出图，请稍等', imageThinking: '正在出图，请稍等。',
  imageOpen: '查看大图', imageDownload: '下载', imageRedo: '重新出', imageLightbox: '已生成的图片',
  uploadImage: '上传图片',
  uploadTooLarge: '这张图超过 8 MB，请换一张小一点的。', uploadUnsupported: '目前只支持 JPEG、PNG、WebP 或 GIF。',
  uploadLimit: '一次最多带 4 张图。', removeAttachment: '移除这张图片',
  storageFailed: '无法打开本地会话存储，请允许浏览器使用本地存储后重试。',
  idle: '准备好开始', signedOut: '尚未登录', pcLogin: '登录后查看你的电脑', pcOnline: '在线',
  pcSessionOrigin: '电脑会话 · 指令发往当前电脑',
  accountCenter: '个人中心', accountSettings: '账号设置', accountCenterHint: '账号、设备和安全设置', billing: '充值与订阅', billingHint: '查看余额和服务权益', promotion: '推广设置', promotionHint: '邀请与推广中心', billingTitle: '充值与订阅', billingLead: '充值和订阅会使用同一账号体系，金额与权益以上海服务返回为准。', recharge: '充值入口', subscribe: '订阅方案', billingPending: '支付入口正在接入，当前不会发起扣款。', promotionTitle: '推广设置', promotionLead: '推广邀请和收益会绑定你的上海账号。', promotionPending: '推广配置暂未开放，后续会在这里管理。', accountBalance: '账号余额', accountBalanceUnavailable: '余额暂不可读', serviceStatus: '服务状态',
  welcomeEyebrow: '随时沟通 · 接续工作', welcomeKicker: '你的随身智能体',
  welcomeTitle: '从一个想法，\n到一起完成。', welcomeDescription: '把问题、灵感和要做的事带过来。千手陪你理清思路，一步步往前。',
  welcomeTalk: '自然地交流', welcomeTalkDetail: '打字或语音，把想法说清楚。',
  welcomePc: '同账号的电脑', welcomePcDetail: '在一个抽屉里，查看你的远程主机。',
  welcomeContinue: '接着上次聊', welcomeContinueDetail: '独立的会话，留住每一件事的进展。',
  welcomeLogin: '登录千手账号', welcomeExplore: '先看看', welcomeFootnote: '使用你的千手账号，连接上海账号服务',
  splashLabel: '千手 AI 启动', splashTagline: '无极问道 千手执棋', splashMotto: '无极问道\n千手执棋', splashHelp: '帮助', splashHelpDetail: '千手 AI 将连接上海账号服务，登录后开始使用。',
  messageYou: '你', messageCopy: '复制这段', messageCopied: '已复制', messageSpeak: '语音播报', messageSpeaking: '正在播报…', messageSpoken: '播报完成',
  messageSpeakUnavailable: '此浏览器不支持语音播报。', messageSpeakFailed: '语音播报未完成，请稍后重试。',
  messageCopyUnavailable: '此浏览器不支持复制，请长按选择文字。', messageCopyFailed: '复制未完成，请长按选择文字。',
} as const
