/** Chinese account and voice copy shared by this browser's account components. */
export const accountCopy = {
  showPassword: '显示密码', hidePassword: '隐藏密码', title: '个人中心', login: '登录', register: '注册账号', commerce: '充值与订阅', close: '关闭', settings: '个人设置', back: '返回', profile: '个人资料', security: '账号安全', sessions: '登录设备', connections: '连接状态', promotion: '推广中心',
  termsLink: '用户协议', privacyLink: '隐私政策', legalLead: '继续即表示同意', legalAnd: '和',
  verifiedAccount: '上海账号已验证', accountOverviewHint: '身份、权益和设备安全集中在这里管理', accountOnline: '登录状态', accountOnlineValue: '当前设备', accountIdLabel: '账号 ID', accountQuickActions: '常用入口', accountSecurityLabel: '账号安全', accountSecurityValue: '进入设置', accountPlanLabel: '额度与订阅', accountPlanValue: '进入查看', openCommerce: '额度与订阅', openPromotion: '推广中心', openSessions: '登录设备', openSecurity: '账号安全', promotionTitle: '推广中心', promotionHint: '邀请与奖励以服务端结算记录为准。当前移动端只展示接入状态，不显示未经确认的收益。', promotionInvite: '邀请链接', promotionInviteValue: '推广接口待接入', promotionInvited: '已邀请用户', promotionInvitedValue: '服务端未返回', promotionReward: '待结算奖励', promotionRewardValue: '服务端未返回', promotionPending: '推广结算接口尚未接入', promotionPendingHint: '接入真实推广 API 后，这里会显示邀请链接、有效邀请和可提现余额。', copyInvite: '复制邀请链接', promotionUnavailable: '当前没有可复制的推广链接。',
  accountLogin: '账号登录', phoneLogin: '手机号登录', wechatLogin: '微信号登录', methodPending: '登录方式待配置，请先使用账号登录', wechatUnconfigured: '微信登录待配置，请先使用账号登录。', wechatRedirecting: '正在打开微信登录…', registerTitle: '创建千手账号', registerHint: '注册完成后使用新账号登录；不会自动登录。', registerUsername: '用户名（可选）', registerEmail: '邮箱（可选）', registerPassword: '设置密码', registerConfirm: '确认密码', registerCompany: '团队或公司（可选）', registerSubmit: '提交注册', registerSuccess: '注册请求已提交，请使用新账号登录。', backToLogin: '返回账号登录', noIdentity: '请至少填写用户名或邮箱。',
  phoneAuthTitle: '手机验证码登录', phoneRegisterTitle: '手机号注册', phoneAuthHint: '验证码由上海账号服务发送；登录后会验证账号身份。',
  phoneNumber: '中国大陆手机号', phoneCode: '短信验证码', phoneCodeSend: '获取验证码', phoneCodeSending: '正在发送…',
  phoneCodeSent: '验证码已发送至', phoneCodeWait: '稍后可重新获取', phoneCodeExpired: '验证码 5 分钟内有效。',
  phoneInvalid: '请填写有效的中国大陆手机号。', phoneCodeInvalid: '请输入 6 位数字验证码。',
  phoneLoginSubmit: '验证码登录', phoneRegisterSubmit: '验证并注册', phoneRegisterSwitch: '还没有账号？手机号注册',
  phoneLoginSwitch: '已有账号？验证码登录', phoneUsername: '用户名（可选）', phoneAuthFailed: '验证码验证未完成，请稍后重试。',
  authManifesto: '无极问道\n千手执棋', authWelcome: '从一个想法开始，让事情有结果。', planChanged: '套餐信息已更新，请重新查看后确认。', subscriptionInsufficient: '订阅余额不足，请先查看充值与余额说明。', receiptUnconfirmed: '购买回执尚未确认，请重新查询。不要重复建立新的购买。',
  authBrand: '千手 AI', authTagline: '登录上海账号，开始工作', username: '用户名或邮箱', password: '密码', totp: '动态验证码', verify: '验证并登录', submitting: '正在验证…',
  loginHint: '使用千手账号连接上海账号服务。', totpHint: '请输入验证器中的 6 位验证码', sessionOnly: '本次登录只在当前页面有效，刷新页面后需重新登录。',
  loginFailed: '登录未完成，请检查账号、密码或连接设置。', loginRequired: '请先登录后再使用千手 AI。', expired: '登录状态已过期，请重新登录。', failed: '服务暂时不可用，请稍后重试。', forbidden: '当前账号无权执行此操作。', invalid: '提交的内容不符合要求，请检查填写内容。', limited: '操作频繁，请稍后重试。',
  loading: '正在读取…', retry: '重试', logout: '退出登录', logoutHint: '本页已退出；如网络中断，服务器撤销状态需在其他设备核查。',
  displayName: '显示名称', phone: '联系电话', language: '偏好语言', country: '国家或地区', email: '邮箱', accountName: '账号', accountId: '账号 ID',
  unset: '未设置', save: '保存资料', saving: '正在保存…', saved: '资料已保存', profileHint: '用户名和邮箱由上海账号服务管理。',
  passwordTitle: '修改密码', oldPassword: '当前密码', newPassword: '新密码', confirmPassword: '确认新密码', passwordMismatch: '两次输入的新密码不一致。',
  passwordHint: '新密码需 6 至 64 位。修改后所有设备将退出，包括当前页面。', changePassword: '确认修改密码', reauthenticate: '安全设置已更新，所有设备需重新登录。',
  totpTitle: '二次验证', enabled: '已开启', disabled: '未开启', totpSetup: '设置二次验证', totpDisable: '关闭二次验证', totpHintSetup: '在验证器中手动添加下方密钥，再输入 6 位验证码。关闭此页会丢弃本次设置。', secret: '验证器密钥', confirmTotp: '确认开启并重新登录', confirmDisable: '确认关闭并重新登录', securityHint: '开启或关闭二次验证后，所有设备需重新登录。',
  sessionsHint: '这里只管理账号登录会话；电脑在线状态请查看“我的电脑”。', current: '当前设备', unknownDevice: '未命名设备', active: '有效', revoked: '已撤销', expiredSession: '已过期', unknownStatus: '状态未提供',
  lastSeen: '最近活动', revoke: '撤销此设备登录', revokeOthers: '退出其他设备', confirmRevoke: '确认撤销', confirmOthers: '确认退出其他设备', cancel: '取消', noSessions: '服务器未返回登录设备',
  voiceStart: '按住说话', voiceActive: '正在聆听…', voiceStop: '结束语音输入',
  voiceHoldHint: '说完后抬手，上滑可取消', voiceCancelHint: '继续上滑，抬手取消', voiceReleaseSend: '识别完成后自动发送', voiceAutoSending: '文字已识别，马上发送；可修改或取消',
  voiceChecking: '正在检查语音支持…', voiceStarting: '正在准备语音输入…', voiceListening: '正在聆听…', voiceStopping: '正在整理成文字…', voiceReady: '文字已放入输入框，请检查后发送。',
  voiceErrors: {
    unsupported: '此浏览器暂不支持语音识别。', 'local-unavailable': '此浏览器暂不支持本机语音识别。', 'language-unavailable': '当前语言尚不能在本机识别。',
    'permission-denied': '麦克风权限被拒绝，请在浏览器设置中允许后重试。', 'no-device': '无法使用麦克风，请检查设备是否连接或被占用。', network: '语音服务连接失败，请稍后重试。',
    'no-speech': '没有听到语音，请重新开始。', aborted: '本次语音已取消。', 'recognition-failed': '语音识别未完成，请重新尝试。', 'consent-required': '使用浏览器语音服务前，需要你明确同意。',
  },
  interactionSettings: '交互偏好', soundEffects: '轻盈提示音', soundEffectsHint: '发送、接收与开始语音时播放轻声提示。', voiceAutoSend: '识别完成后自动发送', voiceAutoSendHint: '默认先把文字放入输入框；开启后会短暂预览，仍可修改或取消。', messageSpeechVoice: '朗读声线', messageSpeechVoiceSystem: '系统自动选择', messageSpeechVoiceHint: '优先使用设备提供的中文声线，速度保持舒缓；没有可选声线时回退到系统默认。', messageSpeechVoiceUnavailable: '设备暂未提供可选声线，将使用系统默认。',
  home: '我的账号', homeIntro: '管理你的身份、额度与连接', accountSection: '账号与服务', settingsSection: '账号设置', serviceSection: '服务与帮助', editProfile: '编辑资料', unknown: '暂未读取', quotaHint: '额度以服务端实际记录为准', subscriptionCenter: '订阅中心', rechargeCenter: '充值中心', orders: '充值记录', noOrders: '暂无充值记录', ordersHint: '展示当前上海账号最近 30 笔充值订单。', rechargeHint: '通过上海现有收银台完成充值；支付结果以订单状态为准。', wallet: '前往上海收银台', walletHint: '将在新窗口打开现有充值模块，请确认登录同一个千手账号。', separateBalance: '上海账户余额与 AI 订阅余额分别记账；充值后请核对到账范围。', channelTitle: '支付方式', channelAvailable: '通道可用', channelUnavailable: '暂不可用', channelReadFailed: '暂时无法查询支付通道，请稍后重试。', onlinePayment: '在线支付', alipay: '支付宝', wechatPay: '微信支付', manualPay: '人工核账', bankTransfer: '银行转账', currentPlan: '当前订阅', planMonth: '一个月', perMonth: '/月', monthlyQuota: '每月额度', selectPlan: '选择此套餐', freePlan: '免费使用', unavailablePrice: '价格暂未提供', subscriptionBalance: 'AI 订阅余额', confirmSubscription: '确认订阅', confirmPurchase: '确认余额支付', purchaseHint: '一次购买一个月，不自动续费。确认后将从 AI 订阅余额中扣除。', purchaseUnconfirmed: '购买结果暂未确认，请查询额度或使用同一笔购买重试。', purchaseSucceeded: '订阅已开通', receiptOrder: '订单编号', receiptCost: '实际扣除', receiptExpiry: '有效期至', purchaseRetry: '重试同一笔购买', needBalance: '余额不足，查看充值', unavailableQuote: '无法读取完整报价，暂不能购买', returnPlans: '返回套餐', refresh: '刷新', paid: '已到账', pendingPayment: '待付款或核账', failedPayment: '支付失败', cancelledPayment: '已取消', expiredPayment: '已过期', unrecognizedPayment: '状态待确认', loginDetails: '查看与管理当前账号', settingsHint: '资料与安全设置直接同步到你的千手账号。', versionLabel: '千手 AI · 移动网页',
  commerceHint: '读取千手网关返回的真实额度与套餐；读不到就不显示价格，也不会编造付款成功。', commerceUnavailable: '移动端额度与订阅路由尚未接入当前服务，暂不能在这里充值或购买订阅。', commerceConnecting: '正在接入', commerceLoading: '正在读取额度与套餐…', commerceRetry: '重新读取额度', commerceTier: '当前套餐', commerceRemaining: '本月剩余额度', commercePurchasable: '可购买余额', commercePlans: '订阅套餐', commerceNoPlans: '服务端未返回套餐目录。', commercePaymentPending: '支付通道尚未完成商户配置；当前不会创建订单或扣款。', commerceReadOnly: '当前为只读展示，购买按钮会在真实支付与移动路由验收后开放。', commerceTitle: '额度与订阅', commerceSubtitle: '订阅、余额和生成能力统一在这里管理', commerceCurrentUsage: '使用概览', commerceAvailable: '可用额度', commercePurchase: '充值', commerceSubscribe: '订阅', commercePurchaseUnavailable: '购买入口待接入', commercePlanHint: '套餐价格和权益只显示服务端返回的真实数据。', commerceNoPayment: '当前没有已验证的支付下单接口，因此不会创建订单或扣款。', commerceShanghaiBalance: '上海余额',
} as const

/** Shanghai wallet recharge copy; amounts and order state always come from the account API. */
export const rechargeCopy = {
  title: '账户余额充值', balance: '上海账户余额', yuan: '元', amount: '充值金额', amountHint: '输入金额，精确到分',
  separate: '本次充值进入上海人民币账户。到账以充值账单为准，不会赠送或转入 SP。',
  create: '确认充值金额', confirm: '确认并创建订单', edit: '修改金额', confirming: '请核对本次账户充值金额',
  loading: '正在读取充值信息…', checking: '正在查询订单…', creating: '正在创建订单，请勿重复操作…',
  payment: '前往支付宝支付', wechat: '微信扫码', wechatOtherDevice: '请用另一台设备的微信扫一扫。手机同机唤起尚未接入。',
  wechatScanHelp: '扫码后回到这里查询订单；显示“已到账”才算完成支付。',
  retryPayment: '重取原订单付款参数', refresh: '查询到账状态', orders: '查看充值记录',
  order: '充值订单', pending: '待付款', paid: '已到账', ended: '订单已结束',
  unknown: '充值请求结果暂未确认。请先查询原订单，不要重复创建充值单。',
  pendingHelp: '已有待付款订单，请继续处理原订单。支付页面返回不代表到账。',
  paymentOpened: '已打开支付宝收银台。请完成付款后返回查询，以订单状态为准。',
  unavailable: '充值通道暂不可用，请稍后重试。', invalid: '请填写大于零且最多两位小数的金额。',
  failed: '暂时无法读取充值结果，请查询原订单后再继续。',
  expired: '付款时限已到，请查询订单最终状态。', paused: '自动查询已暂停，可手动查询到账状态。',
  retry: '重新读取', backSubscription: '返回订阅中心', note: '付款前请再次核对订单号与金额。',
} as const
