-- v8_048 · immutable server-side assignment delivery evidence
--
-- A row is written only after the process holding the worker WebSocket
-- successfully completes send_text().  connection_id is generated by the
-- server and is never accepted from a client frame.

BEGIN;

CREATE TABLE IF NOT EXISTS we_assignment_deliveries (
    id                    BIGSERIAL    PRIMARY KEY,
    shard_id              UUID         NOT NULL
        REFERENCES we_shards(id) ON DELETE CASCADE,
    workload_id           UUID         NOT NULL
        REFERENCES we_workloads(id) ON DELETE CASCADE,
    worker_id             UUID         NOT NULL
        REFERENCES we_workers(id) ON DELETE RESTRICT,
    attempt               INTEGER      NOT NULL,
    connection_id         UUID         NOT NULL,
    mode                   VARCHAR(24)  NOT NULL,
    client_version         VARCHAR(40)  NOT NULL DEFAULT '',
    client_build           VARCHAR(128) NOT NULL DEFAULT '',
    protocol_capabilities JSONB        NOT NULL DEFAULT '[]'::jsonb,
    assignment_manifest   JSONB        NOT NULL DEFAULT '{}'::jsonb,
    delivered_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT we_assignment_deliveries_attempt_chk
        CHECK (attempt >= 0),
    CONSTRAINT we_assignment_deliveries_protocol_caps_chk
        CHECK (jsonb_typeof(protocol_capabilities) = 'array'),
    CONSTRAINT we_assignment_deliveries_manifest_chk
        CHECK (jsonb_typeof(assignment_manifest) = 'object'),
    CONSTRAINT we_assignment_deliveries_identity_uq
        UNIQUE (shard_id, attempt, worker_id, connection_id)
);

CREATE INDEX IF NOT EXISTS we_assignment_deliveries_connection_idx
    ON we_assignment_deliveries (connection_id, delivered_at DESC);
CREATE INDEX IF NOT EXISTS we_assignment_deliveries_shard_attempt_idx
    ON we_assignment_deliveries (shard_id, attempt, delivered_at DESC);
CREATE INDEX IF NOT EXISTS we_assignment_deliveries_current_lookup_idx
    ON we_assignment_deliveries
       (shard_id, worker_id, attempt, connection_id, delivered_at DESC);

COMMIT;
